### Load packages

In [99]:
import pandas as pd
import os
import numpy as np
import zipfile
from typing import Union, Dict

### Define parameters and file info

In [ ]:
# data_directory = r"C:\Users\hefla\Documents\Work\IPS\Industry Analysis\MCN"
data_directory = r"..\data"
output_directory = r"..\output"

# -----------------------------------------------------------------------
# DAF-to-DAF data
# -----------------------------------------------------------------------
daf2daf_file = r"MCN_DAF_to_DAF_grants_2023.csv"
daf2daf_path = os.path.join(data_directory, daf2daf_file)
print("DAF-to-DAF CSV file:", daf2daf_path)

# -----------------------------------------------------------------------
# All-DAF data
# -----------------------------------------------------------------------
alldaf_zipfile = r"MCN_all_DAF_grants_2023"
alldaf_path = os.path.join(data_directory, alldaf_zipfile + ".zip")
print("All-DAF zip file:", alldaf_path)

# -----------------------------------------------------------------------
# BMF data
# -----------------------------------------------------------------------
bmf_directory = r"C:\Users\hefla\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\EO BMF Files"
bmf_file = r"UNIFIED_BMF_V1.2"
bmf_path = os.path.join(bmf_directory, bmf_file + ".csv")
print("BMF file:", bmf_path)

# -----------------------------------------------------------------------
# NTEE data
# -----------------------------------------------------------------------
ntee_directory = r"C:\Users\hefla\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV"
ntee_file = r"eo_bmf_extract_narrow_no_filter"
ntee_path = os.path.join(ntee_directory, ntee_file + ".csv")
print("NTEE file:", ntee_path)

# -----------------------------------------------------------------------
# Output files
# -----------------------------------------------------------------------
full_output_file = r"AllDAF_grants.csv"
full_output_path = os.path.join(output_directory, full_output_file)
print("Full output file:", full_output_path)
nod2d_output_file = r"AllDAF_grants_no_DAF2DAF.csv"
nod2doutput_path = os.path.join(output_directory, nod2d_output_file)
print("NoD2D output file:", nod2doutput_path)
grantor_summary_file = r"DAF_grants_summary_by_grantor_NTEE.csv"
grantor_summary_path = os.path.join(output_directory, grantor_summary_file)
print("Grantor Summary file:", grantor_summary_path)
recipient_summary_file = r"DAF_grants_summary_by_recipient_NTEE.csv"
recipient_summary_path = os.path.join(output_directory, recipient_summary_file)
print("Recipient Summary file:", recipient_summary_path)

DAF-to-DAF CSV file: ..\data\MCN_DAF_to_DAF_grants_2023.csv
All-DAF zip file: ..\data\MCN_all_DAF_grants_2023.zip
BMF file: C:\Users\hefla\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\EO BMF Files\UNIFIED_BMF_V1.2.csv
NTEE file: C:\Users\hefla\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\eo_bmf_extract_narrow_no_filter.csv
Full output file: ..\output\AllDAF_grants.csv
NoD2D output file: ..\output\AllDAF_grants_no_DAF2DAF.csv
Grantor Summary file: ..\output\DAF_grants_summary_by_grantor_NTEE.csv
Grantor Summary file: ..\output\DAF_grants_summary_by_recipient_NTEE.csv

In [101]:
# Function to read in zipped files into a dictionary of dataframes

def load_csv_from_zip(src: str) -> Union[pd.DataFrame, Dict[str, pd.DataFrame]]:

    with zipfile.ZipFile(src, "r") as archive:
        # keep only CSV files
        csv_files = [f for f in archive.namelist() if f.lower().endswith(".csv")]

        if len(csv_files) == 0:
            raise ValueError("No CSV files found in the zip archive.")

        # If there is only one CSV file, return a dataframe
        if len(csv_files) == 1:
            with archive.open(csv_files[0]) as file:
                return pd.read_csv(file)

        # Otherwise return a dictionary of dataframes
        dfs = {}
        for filename in csv_files:
            with archive.open(filename) as file:
                dfs[filename] = pd.read_csv(file)

        return dfs

### Load in data

In [102]:
# Load DAF-to-DAF data

daf2daf_raw_df = pd.read_csv(daf2daf_path)

print(daf2daf_raw_df.info())

daf2daf_raw_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1447 entries, 0 to 1446
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Grantor EIN             1447 non-null   int64
 1   Grantor Name            1447 non-null   object
 2   Recipient EIN           1447 non-null   int64
 3   Recipient Name          1447 non-null   object
 4   Cash Grant Amount       1447 non-null   object
 5   Grantor/Recipient Type  1447 non-null   object
dtypes: int64(2), object(4)
memory usage: 68.0+ KB
None

,Grantor EIN,Grantor Name,Recipient EIN,Recipient Name,Cash Grant Amount,Grantor/Recipient Type
0,10782573,ADVISORS CHARITABLE GIFT FUND INC,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,"$204,922",Nat-to-Nat
1,10782573,ADVISORS CHARITABLE GIFT FUND INC,352129262,RENAISSANCE CHARITABLE FOUNDATION INC,"$455,168",Nat-to-Nat
2,10782573,ADVISORS CHARITABLE GIFT FUND INC,527082731,MORGAN STANLEY GLOBAL IMPACT FUNDING TRUST INC,"$220,194",Nat-to-Nat
3,10782573,ADVISORS CHARITABLE GIFT FUND INC,593652538,RAYMOND JAMES CHARITABLE ENDOWMENT FUND,"$254,975",Nat-to-Nat
4,46649138,FIDUCIARY CHARITABLE FOUNDATION DBA FIDUCIARY ...,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,"$10,000",Nat-to-Nat

In [103]:
# Load All-DAF data

alldaf_raw_df = load_csv_from_zip(alldaf_path)

alldaf_raw_df.head()

C:\Users\hefla\AppData\Local\Temp\ipykernel_20380\685997372.py:15: DtypeWarning: Columns (13,14,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file)

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntTbl_VltnMthdUsdDsc,RcpntTbl_NnCshAssstncDsc,USAddrss_AddrssLn2Txt,RcpntTbl_NnCshAssstncAmt,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
# Load BMF data

bmf_raw_df = pd.read_csv(bmf_path)

print(bmf_raw_df.info())

bmf_raw_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3516801 entries, 0 to 3516800
Data columns (total 50 columns):
 #   Column                      Dtype
---  ------                      -----
 0   EIN2                        object
 1   EIN                         float64
 2   NTEE_IRS                    object
 3   NTEE_NCCS                   object
 4   NTEEV2                      object
 5   NCCS_LEVEL_1                object
 6   NCCS_LEVEL_2                object
 7   NCCS_LEVEL_3                object
 8   F990_ORG_ADDR_CITY          object
 9   F990_ORG_ADDR_STATE         object
 10  F990_ORG_ADDR_ZIP           object
 11  F990_ORG_ADDR_STREET        object
 12  CENSUS_CBSA_FIPS            float64
 13  CENSUS_CBSA_NAME            object
 14  CENSUS_BLOCK_FIPS           float64
 15  CENSUS_URBAN_AREA           object
 16  CENSUS_STATE_ABBR           object
 17  CENSUS_COUNTY_NAME          object
 18  ORG_ADDR_FULL               object
 19  ORG_ADDR_MATCH              object
 20  LATITUDE                    float64
 21  LONGITUDE                   float64
 22  GEOCODER_SCORE              float64
 23  GEOCODER_MATCH              object
 24  BMF_SUBSECTION_CODE         float64
 25  BMF_STATUS_CODE             float64
 26  BMF_PF_FILING_REQ_CODE      float64
 27  BMF_ORGANIZATION_CODE       float64
 28  BMF_INCOME_CODE             float64
 29  BMF_GROUP_EXEMPT_NUM        float64
 30  BMF_FOUNDATION_CODE         float64
 31  BMF_FILING_REQ_CODE         float64
 32  BMF_DEDUCTIBILITY_CODE      float64
 33  BMF_CLASSIFICATION_CODE     float64
 34  BMF_ASSET_CODE              float64
 35  BMF_AFFILIATION_CODE        float64
 36  ORG_RULING_DATE             object
 37  ORG_FISCAL_YEAR             float64
 38  ORG_RULING_YEAR             float64
 39  ORG_YEAR_FIRST              int64
 40  ORG_YEAR_LAST               int64
 41  ORG_YEAR_COUNT              int64
 42  ORG_PERS_ICO                object
 43  ORG_NAME_SEC                object
 44  ORG_NAME_CURRENT            object
 45  ORG_FISCAL_PERIOD           int64
 46  F990_TOTAL_REVENUE_RECENT   float64
 47  F990_TOTAL_INCOME_RECENT    float64
 48  F990_TOTAL_ASSETS_RECENT    float64
 49  F990_TOTAL_EXPENSES_RECENT  float64
dtypes: float64(24), int64(4), object(22)
memory usage: 1.3+ GB
None

,EIN2,EIN,NTEE_IRS,NTEE_NCCS,NTEEV2,NCCS_LEVEL_1,NCCS_LEVEL_2,NCCS_LEVEL_3,F990_ORG_ADDR_CITY,F990_ORG_ADDR_STATE,...,ORG_YEAR_LAST,ORG_YEAR_COUNT,ORG_PERS_ICO,ORG_NAME_SEC,ORG_NAME_CURRENT,ORG_FISCAL_PERIOD,F990_TOTAL_REVENUE_RECENT,F990_TOTAL_INCOME_RECENT,F990_TOTAL_ASSETS_RECENT,F990_TOTAL_EXPENSES_RECENT
0,EIN-00-0000000,0.0,Z99,NaN,NaN,501CX NONPROFIT,O,UN,NaN,NaN,...,1996,1,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN
1,EIN-00-0000000,0.0,Z99,NaN,NaN,501CX NONPROFIT,O,UN,NaN,NaN,...,1996,1,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN
2,EIN-00-0000000,0.0,Z99,NaN,NaN,501CX NONPROFIT,O,UN,NaN,NaN,...,1996,1,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN
3,EIN-00-0000000,0.0,Z99,NaN,NaN,501CX NONPROFIT,O,UN,NaN,NaN,...,1996,1,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN
4,EIN-00-0000000,0.0,Z99,NaN,NaN,501CX NONPROFIT,O,UN,NaN,NaN,...,1996,1,NaN,NaN,NaN,6,NaN,63116.0,21317.0,NaN

In [105]:
# Load in NTEE data

ntee_raw_df = pd.read_csv(ntee_path)

print(ntee_raw_df.info())

ntee_raw_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3516801 entries, 0 to 3516800
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   EIN                  float64
 1   ORG_YEAR_LAST        int64
 2   ORG_NAME_CURRENT     object
 3   BMF_SUBSECTION_CODE  float64
 4   F990_ORG_ADDR_STATE  object
 5   NCCS_LEVEL_1         object
 6   NTEE_IRS             object
 7   NTEE_NCCS            object
 8   NTEEV2               object
 9   NTEE_COMBINED        object
dtypes: float64(2), int64(1), object(7)
memory usage: 268.3+ MB
None

,EIN,ORG_YEAR_LAST,ORG_NAME_CURRENT,BMF_SUBSECTION_CODE,F990_ORG_ADDR_STATE,NCCS_LEVEL_1,NTEE_IRS,NTEE_NCCS,NTEEV2,NTEE_COMBINED
0,0.0,1996,NaN,NaN,NaN,501CX NONPROFIT,Z99,NaN,NaN,Z99
1,0.0,1996,NaN,NaN,NaN,501CX NONPROFIT,Z99,NaN,NaN,Z99
2,0.0,1996,NaN,NaN,NaN,501CX NONPROFIT,Z99,NaN,NaN,Z99
3,0.0,1996,NaN,NaN,NaN,501CX NONPROFIT,Z99,NaN,NaN,Z99
4,0.0,1996,NaN,NaN,NaN,501CX NONPROFIT,Z99,NaN,NaN,Z99

### Clean and format columns

In [106]:
# Clean & format columns in DAF2DAF data

daf2daf_clean_df = daf2daf_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["Grantor EIN", "Recipient EIN"]
daf2daf_clean_df[int_cols] = daf2daf_clean_df[int_cols].astype("Int64")

# Clean up dollar formatting in CSV file
daf2daf_clean_df["Cash Grant Amount"] = (
    daf2daf_clean_df["Cash Grant Amount"]
        .str.replace(r"[$,]", "", regex=True)
        .astype(float)
)
# Convert to float
daf2daf_clean_df["Cash Grant Amount"] = daf2daf_clean_df["Cash Grant Amount"].astype(float)

daf2daf_clean_df.head()

,Grantor EIN,Grantor Name,Recipient EIN,Recipient Name,Cash Grant Amount,Grantor/Recipient Type
0,10782573,ADVISORS CHARITABLE GIFT FUND INC,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,204922.0,Nat-to-Nat
1,10782573,ADVISORS CHARITABLE GIFT FUND INC,352129262,RENAISSANCE CHARITABLE FOUNDATION INC,455168.0,Nat-to-Nat
2,10782573,ADVISORS CHARITABLE GIFT FUND INC,527082731,MORGAN STANLEY GLOBAL IMPACT FUNDING TRUST INC,220194.0,Nat-to-Nat
3,10782573,ADVISORS CHARITABLE GIFT FUND INC,593652538,RAYMOND JAMES CHARITABLE ENDOWMENT FUND,254975.0,Nat-to-Nat
4,46649138,FIDUCIARY CHARITABLE FOUNDATION DBA FIDUCIARY ...,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,10000.0,Nat-to-Nat

In [107]:
# Clean & format columns in All-DAF data

alldaf_clean_df = alldaf_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["Object ID", "EIN", "Year of Tax Period End Date", "RcpntTbl_RcpntEIN", "USAddrss_ZIPCd"]
alldaf_raw_df[int_cols] = alldaf_raw_df[int_cols].astype("Int64")

# Clean up dollar formatting in CSV file
dollar_cols = ["RcpntTbl_CshGrntAmt", "RcpntTbl_NnCshAssstncAmt"]
# Convert to float
alldaf_clean_df[dollar_cols] = alldaf_clean_df[dollar_cols].astype(float)

alldaf_clean_df.head()

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntTbl_VltnMthdUsdDsc,RcpntTbl_NnCshAssstncDsc,USAddrss_AddrssLn2Txt,RcpntTbl_NnCshAssstncAmt,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
# QC revenue

print(alldaf_clean_df["RcpntTbl_CshGrntAmt"].sum())

62004522644.0

### Clean, format, and filter columns in BMF data

In [109]:
# Filter BMF rows to only those where the ORG_YEAR_LAST is no earlier than the earliest year we want

earliest_year = 0

print("Before filtering:", len(bmf_raw_df))
bmf_filtered_df = bmf_raw_df[bmf_raw_df["ORG_YEAR_LAST"] >= earliest_year]
print("After filtering:", len(bmf_filtered_df))

Before filtering: 3516801
After filtering: 3516801

In [110]:
# QC BMF versus NCCS codes

# Function to get first letter of a column's values
# def get_first_letter(series):
#     return series.astype(str).str[0].where(series.notna(), None)
def get_first_letter(series):
    return series.astype(str).str[0]

# Get counts

# BMF counts
bmf_nccs_counts = get_first_letter(bmf_filtered_df["NTEE_NCCS"]).value_counts()
bmf_irs_counts  = get_first_letter(bmf_filtered_df["NTEE_IRS"]).value_counts()

# NCCS counts
nccs_nccs_counts = get_first_letter(ntee_raw_df["NTEE_NCCS"]).value_counts()
nccs_irs_counts  = get_first_letter(ntee_raw_df["NTEE_IRS"]).value_counts()

# Combine into a table
comparison_df = pd.DataFrame({
    "bmf_NTEE_NCCS": bmf_nccs_counts,
    "bmf_NTEE_IRS":  bmf_irs_counts,
    "nccs_NTEE_NCCS": nccs_nccs_counts,
    "nccs_NTEE_IRS":  nccs_irs_counts
}).fillna(0).astype(int)

# Sort by letter
comparison_df = comparison_df.sort_index()

comparison_df

   bmf_NTEE_NCCS  bmf_NTEE_IRS  nccs_NTEE_NCCS  nccs_NTEE_IRS
0              6            28               6             28
5              0             1               0              1
8              0             1               0              1
A         251921        260274          251921         260274
B         448761        458230          448761         458230
C          65754         67922           65754          67922
D          61272         61307           61272          61307
E         102968        108474          102968         108474
F          48389         50179           48389          50179
G          56341         56804           56341          56804
H          11202         11641           11202          11641
I          42159         43682           42159          43682
J          75224         75665           75224          75665
K          40107         40918           40107          40918
L          67657         69342           67657          69342
M          48066         49480           48066          49480
N         282208        287334          282208         287334
O         140999        141654          140999         141654
P         277166        285984          277166         285984
Q          47034         46906           47034          46906
R          28962         29913           28962          29913
S         264714        265291          264714         265291
T         224460        236117          224460         236117
U          22323         22827           22323          22827
V           4751          5025            4751           5025
W         158612        156612          158612         156612
X         440646        440735          440646         440735
Y         136779        136929          136779         136929
Z          49308         53572           49308          53572
c              0             3               0              3
n         118689         53777          118689          53777
w            323           174             323            174

### Clean and format columns in NTEE data

In [111]:
ntee_raw_df.columns

Index(['EIN', 'ORG_YEAR_LAST', 'ORG_NAME_CURRENT', 'BMF_SUBSECTION_CODE',
       'F990_ORG_ADDR_STATE', 'NCCS_LEVEL_1', 'NTEE_IRS', 'NTEE_NCCS',
       'NTEEV2', 'NTEE_COMBINED'],
      dtype='object')

In [112]:
# Clean & format columns in NTEE data

ntee_clean_df = ntee_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["EIN", "BMF_SUBSECTION_CODE"]
ntee_clean_df[int_cols] = ntee_clean_df[int_cols].astype("Int64")

# Drop unnecessary columns
cols_to_drop = ["F990_ORG_ADDR_STATE", "NCCS_LEVEL_1", "NTEE_IRS", "NTEE_NCCS", "NTEEV2"]
ntee_clean_df = ntee_clean_df.drop(columns=cols_to_drop)

# Uppercase NTEE_COMBINED
ntee_clean_df["NTEE_COMBINED"] = ntee_clean_df["NTEE_COMBINED"].str.upper()

# Create one-digit NTEE code columm
ntee_clean_df["NTEE_FIRST_DIGIT"] = ntee_clean_df["NTEE_COMBINED"].str[0]

# Identify invalid first digits (not A-Z or null/NaN) and replace with "0"
ntee_clean_df["NTEE_FIRST_DIGIT"] = ntee_clean_df["NTEE_FIRST_DIGIT"].mask(
    ntee_clean_df["NTEE_FIRST_DIGIT"].isna() | ~ntee_clean_df["NTEE_FIRST_DIGIT"].str.match(r"^[A-Z]$", na=False),
    "0"
)

ntee_clean_df.head()

,EIN,ORG_YEAR_LAST,ORG_NAME_CURRENT,BMF_SUBSECTION_CODE,NTEE_COMBINED,NTEE_FIRST_DIGIT
0,0,1996,NaN,<NA>,Z99,Z
1,0,1996,NaN,<NA>,Z99,Z
2,0,1996,NaN,<NA>,Z99,Z
3,0,1996,NaN,<NA>,Z99,Z
4,0,1996,NaN,<NA>,Z99,Z

In [113]:
# Find records where NTEE_COMBINED is null or 0

# Rows where NTEE_FIRST_DIGIT is NaN or not A-Z
invalid_ntee_rows = ntee_clean_df[
    ntee_clean_df["NTEE_FIRST_DIGIT"].isna() |        # null/NaN
    ~ntee_clean_df["NTEE_FIRST_DIGIT"].str.match(r"^[A-Z]$", na=False)  # not a single uppercase letter
]

# print(invalid_ntee_rows.value_counts())
# Show the results
# print(invalid_ntee_rows)
print("Number of invalid NTEE codes:", len(invalid_ntee_rows))

Number of invalid NTEE codes: 53806

In [114]:
# Dedupe the NTEE file

ntee_valid_df = ntee_clean_df.copy()
print("Before deduping:", len(ntee_valid_df))

# Find rows with valid NTEE codes
ntee_valid_df["is_valid_ntee"] = (
    ntee_valid_df["NTEE_FIRST_DIGIT"]
    .astype(str)
    .str.match("^[A-Za-z]$")
)

# Make sure the year is numeric
ntee_valid_df["ORG_YEAR_LAST"] = pd.to_numeric(ntee_valid_df["ORG_YEAR_LAST"], errors="coerce")

# Sort by EIN, valid ntee code flag, and ORG_YEAR_LAST
ntee_sorted_df = ntee_valid_df.sort_values(
    by=["EIN", "is_valid_ntee", "ORG_YEAR_LAST"],
    ascending=[True, False, False]
)

# Keep only the first record for each EIN
ntee_dedupe_df = ntee_sorted_df.drop_duplicates(subset="EIN", keep="first")

# Drop the helper column
ntee_dedupe_df = ntee_dedupe_df.drop(columns=["is_valid_ntee"])

print("After deduping:", len(ntee_dedupe_df))

ntee_dedupe_df.head()

Before deduping: 3516801
After deduping: 3436970

,EIN,ORG_YEAR_LAST,ORG_NAME_CURRENT,BMF_SUBSECTION_CODE,NTEE_COMBINED,NTEE_FIRST_DIGIT
0,0,1996,NaN,<NA>,Z99,Z
16,1,2017,VOLUNTEERS OF AMERICA INC,3,B43,B
17,4,2001,SCRIPT INC,3,B90,B
18,5,2004,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3,A50,A
19,3154,2017,OAKLEAF FOREST TENANT MANAGEMENT,3,C36,C

In [115]:
# Check presence of duplicate rows
duplicates_df = ntee_dedupe_df[ntee_dedupe_df["EIN"].duplicated(keep=False)]

print(f"Total duplicate rows: {len(duplicates_df)}")
# duplicates_df.head(10)

Total duplicate rows: 0

### Add NTEE codes to All-DAF grants file

In [116]:
# Add NTEE codes for grantors

print("Before merging:", len(alldaf_clean_df))
print(alldaf_clean_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_grantor_ntee_df = (
    alldaf_clean_df
    .merge(
        ntee_dedupe_df[["EIN", "NTEE_COMBINED", "NTEE_FIRST_DIGIT"]],
        left_on=["EIN"],
        right_on=["EIN"],
        how="left",
        indicator=True
    )
)

# Drop helper columns
alldaf_grantor_ntee_df = alldaf_grantor_ntee_df.drop(columns=["_merge"])

# Rename columns
alldaf_grantor_ntee_df = alldaf_grantor_ntee_df.rename(
    columns={
        "NTEE_COMBINED": "GRANTOR_NTEE_COMBINED",
        "NTEE_FIRST_DIGIT": "GRANTOR_NTEE_FIRST_DIGIT"
    }
)

print("After merging:", len(alldaf_grantor_ntee_df))
print(alldaf_grantor_ntee_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_grantor_ntee_df.head()

Before merging: 518889
62004522644.0
After merging: 518889
62004522644.0

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,USAddrss_AddrssLn2Txt,RcpntTbl_NnCshAssstncAmt,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T

In [117]:
# Add NTEE codes for recipients

print("Before merging:", len(alldaf_grantor_ntee_df))

# Select only the relevant columns from ntee_dedupe_df
recipient_ntee_df = ntee_dedupe_df[["EIN", "NTEE_COMBINED", "NTEE_FIRST_DIGIT"]].rename(
    columns={
        "EIN": "RECIPIENT_EIN",
        "NTEE_COMBINED": "RECIPIENT_NTEE_COMBINED",
        "NTEE_FIRST_DIGIT": "RECIPIENT_NTEE_FIRST_DIGIT"
    }
)

alldaf_allntee_df = alldaf_grantor_ntee_df.merge(
    recipient_ntee_df,
    left_on="RcpntTbl_RcpntEIN",
    right_on="RECIPIENT_EIN",
    how="left"
)

# Drop the merge helper columns
alldaf_allntee_df = alldaf_allntee_df.drop(columns=["RECIPIENT_EIN"])
alldaf_allntee_df = alldaf_allntee_df.drop(columns=["_merge"], errors="ignore")

print("After merging:", len(alldaf_allntee_df))
print(alldaf_allntee_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_allntee_df.head()

Before merging: 518889
After merging: 518889
62004522644.0

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,A6E,A
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,C60,C
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,L24,L
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,C35,C
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,A65,A

### Remove DAF-to-DAF grants from All-DAF grants

In [118]:
# Find DAF2DAF duplicates in All-DAF grants list

# Find the matching rows in the 2 dataframes
matched = alldaf_allntee_df.merge(
    daf2daf_clean_df[["Grantor EIN", "Recipient EIN"]],
    left_on=["EIN", "RcpntTbl_RcpntEIN"],
    right_on=["Grantor EIN", "Recipient EIN"],
    how="inner"
)

# Identify duplicates in those rows
duplicates = matched[
    matched.duplicated(
        subset=["EIN", "RcpntTbl_RcpntEIN"],
        keep=False
    )
]

duplicates = duplicates.sort_values(["EIN", "RcpntTbl_RcpntEIN"])
print(duplicates[["EIN", "RcpntTbl_RcpntEIN", "RcpntTbl_CshGrntAmt"]])

            EIN  RcpntTbl_RcpntEIN  RcpntTbl_CshGrntAmt
18     46649138        510198509.0            1000000.0
19     46649138        510198509.0             761146.0
20     61676688        341747398.0           76391938.0
25     61676688        341747398.0           86191082.0
26     61676688        516506426.0              14181.0
...         ...                ...                  ...
1445  841260437        110303001.0               5822.0
1484  943136771        943136771.0              40850.0
1485  943136771        943136771.0             241000.0
1486  946070996        943136771.0              37500.0
1492  946070996        943136771.0              40000.0

[137 rows x 3 columns]

In [119]:
# Remove DAF2DAF grants from All-DAF grants list

print("Before filtering:", len(alldaf_allntee_df))
print("Records in DAF2DAF list:", len(daf2daf_clean_df))

alldaf_filtered_df = (
    alldaf_allntee_df
    .merge(
        daf2daf_clean_df[["Grantor EIN", "Recipient EIN"]],
        left_on=["EIN", "RcpntTbl_RcpntEIN"],
        right_on=["Grantor EIN", "Recipient EIN"],
        how="left",
        indicator=True
    )
)

# Keep only rows that did NOT match
alldaf_filtered_df = alldaf_filtered_df[alldaf_filtered_df["_merge"] == "left_only"]

# Drop helper columns
alldaf_filtered_df = alldaf_filtered_df.drop(columns=["Grantor EIN", "Recipient EIN", "_merge"])

print("After filtering:", len(alldaf_filtered_df))
print(alldaf_filtered_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_filtered_df.head()

Before filtering: 518889
Records in DAF2DAF list: 1447
After filtering: 517353
57017667108.0

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,A6E,A
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,C60,C
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,L24,L
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,C35,C
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,A65,A

### Create summaries by NTEE code

In [120]:
# Check for missing values in RECIPIENT_NTEE_FIRST_DIGIT
missing_count = alldaf_allntee_df["GRANTOR_NTEE_FIRST_DIGIT"].isna().sum()
print(f"Missing GRANTOR_NTEE_FIRST_DIGIT in alldaf_allntee_df: {missing_count}")

missing_filtered_count = alldaf_filtered_df["GRANTOR_NTEE_FIRST_DIGIT"].isna().sum()
print(f"Missing GRANTOR_NTEE_FIRST_DIGIT in alldaf_filtered_df: {missing_filtered_count}")

# Optionally, see which values are invalid (not a letter A-Z or 0)
invalid_values = alldaf_allntee_df.loc[
    ~alldaf_allntee_df["GRANTOR_NTEE_FIRST_DIGIT"].astype(str).str.match("^[A-Z0-9]$"),
    "GRANTOR_NTEE_FIRST_DIGIT"
].unique()
print(f"Other invalid GRANTOR_NTEE_FIRST_DIGIT values: {invalid_values}")

Missing GRANTOR_NTEE_FIRST_DIGIT in alldaf_allntee_df: 6
Missing GRANTOR_NTEE_FIRST_DIGIT in alldaf_filtered_df: 6
Other invalid GRANTOR_NTEE_FIRST_DIGIT values: [nan]

In [121]:
# Check for missing values in RECIPIENT_NTEE_FIRST_DIGIT
missing_count = alldaf_allntee_df["RECIPIENT_NTEE_FIRST_DIGIT"].isna().sum()
print(f"Missing RECIPIENT_NTEE_FIRST_DIGIT in alldaf_allntee_df: {missing_count}")

missing_filtered_count = alldaf_filtered_df["RECIPIENT_NTEE_FIRST_DIGIT"].isna().sum()
print(f"Missing RECIPIENT_NTEE_FIRST_DIGIT in alldaf_filtered_df: {missing_filtered_count}")

# Optionally, see which values are invalid (not a letter A-Z or 0)
invalid_values = alldaf_allntee_df.loc[
    ~alldaf_allntee_df["RECIPIENT_NTEE_FIRST_DIGIT"].astype(str).str.match("^[A-Z0-9]$"),
    "RECIPIENT_NTEE_FIRST_DIGIT"
].unique()
print(f"Other invalid RECIPIENT_NTEE_FIRST_DIGIT values: {invalid_values}")

Missing RECIPIENT_NTEE_FIRST_DIGIT in alldaf_allntee_df: 58887
Missing RECIPIENT_NTEE_FIRST_DIGIT in alldaf_filtered_df: 58887
Other invalid RECIPIENT_NTEE_FIRST_DIGIT values: [nan]

In [130]:
alldaf_allntee_df.columns

Index(['Object ID', 'EIN', 'Organization Name', 'Year of Tax Period End Date',
       'RcpntBsnssNm_BsnssNmLn1Txt', 'USAddrss_AddrssLn1Txt', 'USAddrss_CtyNm',
       'USAddrss_SttAbbrvtnCd', 'USAddrss_ZIPCd', 'RcpntTbl_RcpntEIN',
       'RcpntTbl_IRCSctnDsc', 'RcpntTbl_CshGrntAmt', 'RcpntTbl_PrpsOfGrntTxt',
       'RcpntTbl_VltnMthdUsdDsc', 'RcpntTbl_NnCshAssstncDsc',
       'USAddrss_AddrssLn2Txt', 'RcpntTbl_NnCshAssstncAmt',
       'RcpntBsnssNm_BsnssNmLn2Txt', 'FrgnAddrss_AddrssLn1Txt',
       'FrgnAddrss_CtyNm', 'FrgnAddrss_CntryCd', 'FrgnAddrss_PrvncOrSttNm',
       'FrgnAddrss_FrgnPstlCd', 'GRANTOR_NTEE_COMBINED',
       'GRANTOR_NTEE_FIRST_DIGIT', 'RECIPIENT_NTEE_COMBINED',
       'RECIPIENT_NTEE_FIRST_DIGIT'],
      dtype='object')

In [122]:
# GRANTOR Summary for the full/clean dataframe

# Full/clean summary
summary_original = (
    alldaf_allntee_df
    .groupby("GRANTOR_NTEE_FIRST_DIGIT", as_index=False, dropna=False)  # keep NaNs as groups
    .agg(
        Total_Cash_Grants_Original=("RcpntTbl_CshGrntAmt", "sum"),
        Count_Original=("RcpntTbl_CshGrntAmt", "count")
    )
)

# Filtered summary
summary_no_DAF2DAF = (
    alldaf_filtered_df
    .groupby("GRANTOR_NTEE_FIRST_DIGIT", as_index=False, dropna=False)
    .agg(
        Total_Cash_Grants_No_DAF2DAF=("RcpntTbl_CshGrntAmt", "sum"),
        Count_No_DAF2DAF=("RcpntTbl_CshGrntAmt", "count")
    )
)

# Merge with outer join
grantor_summary_combined = summary_original.merge(
    summary_no_DAF2DAF,
    on="GRANTOR_NTEE_FIRST_DIGIT",
    how="outer"
)

# Difference columns
grantor_summary_combined["DAF2DAF_Grants"] = (
    grantor_summary_combined["Total_Cash_Grants_Original"] - 
    grantor_summary_combined["Total_Cash_Grants_No_DAF2DAF"]
)
grantor_summary_combined["Count_DAF2DAF_Grants"] = (
    grantor_summary_combined["Count_Original"] - 
    grantor_summary_combined["Count_No_DAF2DAF"]
)

# Optional: sort so NaNs come first
grantor_summary_combined = grantor_summary_combined.sort_values(
    by="GRANTOR_NTEE_FIRST_DIGIT", na_position="first"
)

grantor_summary_combined.head(30)

# print(grantor_summary_combined["Total_Cash_Grants_No_DAF2DAF"].sum())

,GRANTOR_NTEE_FIRST_DIGIT,Total_Cash_Grants_Original,Count_Original,Total_Cash_Grants_No_DAF2DAF,Count_No_DAF2DAF,DAF2DAF_Grants,Count_DAF2DAF_Grants
26,NaN,8.681300e+04,6,8.681300e+04,6,0.000000e+00,0
0,0,1.134554e+07,29,1.134554e+07,29,0.000000e+00,0
1,A,3.217522e+07,487,3.217522e+07,487,0.000000e+00,0
2,B,3.557361e+09,9147,3.555562e+09,9134,1.799035e+06,13
3,C,1.201998e+08,262,1.201998e+08,262,0.000000e+00,0
4,D,9.489883e+07,70,9.489883e+07,70,0.000000e+00,0
5,E,1.135029e+09,1034,1.135029e+09,1034,0.000000e+00,0
6,F,4.927540e+05,15,4.927540e+05,15,0.000000e+00,0
7,G,1.048811e+08,585,1.048811e+08,585,0.000000e+00,0
8,H,2.597230e+07,58,2.597230e+07,58,0.000000e+00,0
9,I,4.251466e+07,718,4.156757e+07,712,9.470870e+05,6
10,J,2.085671e+06,28,2.085671e+06,28,0.000000e+00,0
11,K,7.787718e+06,96,7.787718e+06,96,0.000000e+00,0
12,L,2.404709e+06,11,2.404709e+06,11,0.000000e+00,0
13,M,3.101245e+08,9610,3.081618e+08,9597,1.962772e+06,13
14,N,1.180758e+08,481,1.180758e+08,481,0.000000e+00,0
15,O,1.034329e+07,119,1.034329e+07,119,0.000000e+00,0
16,P,1.480382e+08,2294,1.480382e+08,2294,0.000000e+00,0
17,Q,1.779396e+08,1388,1.779396e+08,1388,0.000000e+00,0
18,R,1.136639e+07,348,1.136639e+07,348,0.000000e+00,0
19,S,9.543339e+09,75736,8.675364e+09,75590,8.679755e+08,146
20,T,4.559207e+10,410170,4.159514e+10,408850,3.996935e+09,1320
21,V,3.307875e+07,427,2.966055e+07,420,3.418197e+06,7
22,W,1.983236e+07,647,1.868960e+07,642,1.142759e+06,5
23,X,8.988541e+08,4632,7.861794e+08,4606,1.126747e+08,26
24,Y,6.466200e+04,2,6.466200e+04,2,0.000000e+00,0
25,Z,4.156247e+06,192,4.156247e+06,192,0.000000e+00,0

In [123]:
# Summary for the full/clean dataframe (recipients)

summary_original_recipient = (
    alldaf_allntee_df
    .groupby("RECIPIENT_NTEE_FIRST_DIGIT", as_index=False, dropna=False)
    .agg(
        Total_Cash_Grants_Original=("RcpntTbl_CshGrntAmt", "sum"),
        Count_Original=("RcpntTbl_CshGrntAmt", "count")
    )
)

summary_no_DAF2DAF_recipient = (
    alldaf_filtered_df
    .groupby("RECIPIENT_NTEE_FIRST_DIGIT", as_index=False, dropna=False)
    .agg(
        Total_Cash_Grants_No_DAF2DAF=("RcpntTbl_CshGrntAmt", "sum"),
        Count_No_DAF2DAF=("RcpntTbl_CshGrntAmt", "count")
    )
)

recipient_summary_combined = summary_original_recipient.merge(
    summary_no_DAF2DAF_recipient,
    on="RECIPIENT_NTEE_FIRST_DIGIT",
    how="outer"
)

recipient_summary_combined["DAF2DAF_Grants"] = (
    recipient_summary_combined["Total_Cash_Grants_Original"] - 
    recipient_summary_combined["Total_Cash_Grants_No_DAF2DAF"]
)
recipient_summary_combined["Count_DAF2DAF_Grants"] = (
    recipient_summary_combined["Count_Original"] - 
    recipient_summary_combined["Count_No_DAF2DAF"]
)

recipient_summary_combined = recipient_summary_combined.sort_values(
    by="RECIPIENT_NTEE_FIRST_DIGIT", na_position="first"
)

recipient_summary_combined.head(30)
# print(grantor_summary_combined["Total_Cash_Grants_Original"].sum())
# print(grantor_summary_combined["Total_Cash_Grants_No_DAF2DAF"].sum())

,RECIPIENT_NTEE_FIRST_DIGIT,Total_Cash_Grants_Original,Count_Original,Total_Cash_Grants_No_DAF2DAF,Count_No_DAF2DAF,DAF2DAF_Grants,Count_DAF2DAF_Grants
27,NaN,8.208558e+09,58814,8.208558e+09,58814,0.000000e+00,0
0,0,2.768726e+08,5236,2.765724e+08,5232,3.002130e+05,4
1,A,3.037296e+09,41087,3.036905e+09,41080,3.914000e+05,7
2,B,1.271469e+10,76232,1.267336e+10,76162,4.132790e+07,70
3,C,2.010786e+09,14964,2.010708e+09,14959,7.766300e+04,5
4,D,1.012795e+09,18759,1.012795e+09,18759,0.000000e+00,0
5,E,3.479133e+09,21289,3.478982e+09,21280,1.506080e+05,9
6,F,4.726707e+08,7170,4.726707e+08,7170,0.000000e+00,0
7,G,6.214607e+08,8822,6.214301e+08,8820,3.058600e+04,2
8,H,4.228132e+08,3571,4.228132e+08,3571,0.000000e+00,0
9,I,8.884935e+08,6944,8.858984e+08,6924,2.595142e+06,20
10,J,3.153920e+08,2875,3.153920e+08,2875,0.000000e+00,0
11,K,6.297919e+08,9177,6.268483e+08,9167,2.943647e+06,10
12,L,7.570560e+08,9799,7.570560e+08,9799,0.000000e+00,0
13,M,2.265430e+08,2636,2.264528e+08,2633,9.020700e+04,3
14,N,6.928556e+08,11849,6.926177e+08,11843,2.378910e+05,6
15,O,9.081337e+08,14256,9.081337e+08,14256,0.000000e+00,0
16,P,3.904124e+09,56516,3.901209e+09,56490,2.914410e+06,26
17,Q,2.780414e+09,19049,2.777228e+09,19035,3.186810e+06,14
18,R,1.028562e+09,7943,1.028547e+09,7942,1.500000e+04,1
19,S,1.922891e+09,11965,1.210004e+09,11890,7.128870e+08,75
20,T,7.571442e+09,25022,3.480079e+09,23845,4.091363e+09,1177
21,U,1.745411e+09,1842,1.745411e+09,1842,0.000000e+00,0
22,V,2.674891e+08,1095,2.564828e+08,1085,1.100629e+07,10
23,W,5.944107e+08,5801,5.912186e+08,5768,3.192131e+06,33
24,X,4.991687e+09,70648,4.877542e+09,70584,1.141456e+08,64
25,Y,2.213774e+07,441,2.213774e+07,441,0.000000e+00,0
26,Z,5.006124e+08,4790,5.006124e+08,4790,0.000000e+00,0

In [124]:
print(recipient_summary_combined["Total_Cash_Grants_Original"].sum())
print(recipient_summary_combined["Total_Cash_Grants_No_DAF2DAF"].sum())

62004522644.0
57017667108.0

In [137]:
# Calculate Shonni's summary groupings

def shonni_groups(row):
    code = row["RECIPIENT_NTEE_FIRST_DIGIT"]
    combined = str(row["RECIPIENT_NTEE_COMBINED"]).upper() if pd.notna(row["RECIPIENT_NTEE_COMBINED"]) else ""
    
    if pd.isna(code):
        return None
    
    code = str(code).upper()
    
    if code == "A":
        return "A"
    
    elif code == "B":
        if combined.startswith(("B40", "B41", "B43", "B50")):
            return "Colleges and Universities"
        else:
            return "B"
    
    elif code in ["C", "D"]:
        return "CD"
    
    elif code in ["E", "F", "G", "H"]:
        return "EFGH"
    
    elif code in ["I", "J", "K", "L", "M", "N", "O", "P"]:
        return "IJKLMNOP"
    
    elif code == "Q":
        return "Q"
    
    elif code in ["R", "S", "T", "U", "V", "W"]:
        return "RSTUVW"
    
    elif code == "X":
        return "X"
    
    elif code == "Y":
        return "Y"
    
    elif code == "Z":
        return "Z"
    
    else:
        return None
    
alldaf_allntee_df["NTEE_SHONNI"] = alldaf_allntee_df.apply(shonni_groups, axis=1)

shonni_grouped = (
    alldaf_allntee_df
    .groupby("NTEE_SHONNI", as_index=False)
    .agg(
        Total_Cash_Grants_Original=("RcpntTbl_CshGrntAmt", "sum"),
        Count_Original=("RcpntTbl_CshGrntAmt", "count")
    )
)

alldaf_filtered_df["NTEE_SHONNI"] = alldaf_filtered_df.apply(shonni_groups, axis=1)

shonni_grouped_filtered = (
    alldaf_filtered_df
    .groupby("NTEE_SHONNI", as_index=False)
    .agg(
        Total_Cash_Grants_No_DAF2DAF=("RcpntTbl_CshGrntAmt", "sum"),
        Count_No_DAF2DAF=("RcpntTbl_CshGrntAmt", "count")
    )
)

order = ["A", "B", "Colleges and Universities", "CD", "EFGH", "IJKLMNOP", "Q", "RSTUVW", "X", "Y", "Z"]

shonni_grouped["NTEE_SHONNI"] = pd.Categorical(
    shonni_grouped["NTEE_SHONNI"],
    categories=order,
    ordered=True
)

shonni_combined = shonni_grouped.merge(
    shonni_grouped_filtered,
    on="NTEE_SHONNI",
    how="outer"
)

shonni_combined = shonni_combined.sort_values("NTEE_SHONNI")

shonni_combined

,NTEE_SHONNI,Total_Cash_Grants_Original,Count_Original,Total_Cash_Grants_No_DAF2DAF,Count_No_DAF2DAF
0,A,3.037296e+09,41087,3.036905e+09,41080
1,B,7.025883e+09,64596,6.985126e+09,64538
2,CD,3.023581e+09,33723,3.023504e+09,33718
3,Colleges and Universities,5.688807e+09,11636,5.688236e+09,11624
4,EFGH,4.996077e+09,40852,4.995896e+09,40841
5,IJKLMNOP,8.322389e+09,114052,8.313608e+09,113987
6,Q,2.780414e+09,19049,2.777228e+09,19035
7,RSTUVW,1.313021e+10,53668,8.311742e+09,52372
8,X,4.991687e+09,70648,4.877542e+09,70584
9,Y,2.213774e+07,441,2.213774e+07,441
10,Z,5.006124e+08,4790,5.006124e+08,4790

In [148]:
# Select some random societal benefit orgs

sample_size = 25

socben_subset = alldaf_allntee_df[
    alldaf_allntee_df["RECIPIENT_NTEE_FIRST_DIGIT"].isin(["R", "S", "T", "U", "V", "W"])
]

socben_sample = socben_subset.sample(n=sample_size, random_state=77)  # random_state for reproducibility

socben_sample

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT,NTEE_SHONNI
108684,202432509349301128,202454729,COMMUNITIES OF COASTAL GEORGIA FOUNDATION INC,2023,GEORGIA PUBLIC BROADCASTING,260 14TH STREET NW,ATLANTA,GA,30318.0,581510475.0,...,NaN,NaN,NaN,NaN,NaN,T31,T,W115,W,RSTUVW
176321,202443189349305024,262048480,IMPACTASSETSINC,2023,AMERICAN FRIENDS OF RUACH TOVA,215 COUDERT PLACE,SOUTH ORANGE,NJ,7079.0,800163835.0,...,NaN,NaN,NaN,NaN,NaN,T70,T,T40,T,RSTUVW
363130,202403209349313980,527082731,MORGAN STANLEY GLOBAL IMPACT FUNDING TRUST INC,2023,BOSTON FOUNDATION,75 ARLINGTON ST,BOSTON,MA,21163.0,42104021.0,...,NaN,NaN,NaN,NaN,NaN,T90,T,T31,T,RSTUVW
458977,202410469349300741,810739440,AMERICAN ONLINE GIVING FOUNDATION INC,2023,FRIENDS OF IVANHOE SCHOOL,2828 HERKIMER ST,LOS ANGELES,CA,900390985.0,954503051.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,T01,T,RSTUVW
227134,202411039349301716,311640316,SCHWAB CHARITABLE FUND,2023,CHILDREN'S CHARITY,1600 WEST LOOP SUITE 610,HOUSTON,TX,77027.0,760135741.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,S81,S,RSTUVW
504535,202443139349303424,916013536,SEATTLE FOUNDATION,2023,SKYLIGHT PICTURES AND ENGAGEMENT,147 PRINCE ST 3RD FL,BROOKLYN,NY,112013022.0,465530678.0,...,NaN,NaN,NaN,NaN,NaN,T31,T,R60,R,RSTUVW
355470,202423189349304787,522166327,DONORS TRUST INC,2023,INSTITUTE FOR ADVANCED STUDY,1 EINSTEIN DRIVE,PRINCETON,NJ,8540.0,210634988.0,...,NaN,NaN,NaN,NaN,NaN,T99,T,U05,U,RSTUVW
428092,202413059349302646,680480736,NETWORK FOR GOOD,2023,PRECIOUS PROJECT INC,231 BUSSEY ST,DEDHAM,MA,90720.0,471281673.0,...,NaN,NaN,NaN,NaN,NaN,M19,M,T12,T,RSTUVW
262192,202442479349301654,341747398,AMERICAN ENDOWMENT FOUNDATION,2023,CONTRA COSTA YOUTH COUNCIL,3411 MCELLEN CT,LAFAYETTE,CA,945495133.0,911773198.0,...,NaN,NaN,NaN,NaN,NaN,T31,T,W70,W,RSTUVW
220359,202411039349301716,311640316,SCHWAB CHARITABLE FUND,2023,HUMANIST GLOBAL CHARITY,99 PINEHURST ROAD,CANYON,CA,94516.0,463953105.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,W99,W,RSTUVW
18510,202441369349301334,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,2023,INDIGENOUS MEDICINE CONSERVATION FUND,150 ALMAR AVE 475,SANTA CRUZ,CA,95060.0,873761970.0,...,NaN,NaN,NaN,NaN,NaN,S50,S,T30,T,RSTUVW
473818,202410469349300741,810739440,AMERICAN ONLINE GIVING FOUNDATION INC,2023,SAN DIEGO COUNTY PROSPERITY FOUNDATION,PO BOX 720332,SAN DIEGO,CA,921720332.0,461924716.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,W19,W,RSTUVW
281441,202430789349300118,363245072,THE ROTARY FOUNDATION OF ROTARY INTERNATIONAL,2023,ROTARY DISTRICT 5390,2600 MAIN ST SUITE 1,MILES CITY,MT,59301.0,816012488.0,...,NaN,NaN,NaN,NaN,NaN,Q1134,Q,S80,S,RSTUVW
406868,202430469349302713,593652538,RAYMOND JAMES CHARITABLE ENDOWMENT FUND,2023,JUDI'S HOUSE,10125 E 25TH AVE,AURORA,CO,80010.0,841600797.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,T30,T,RSTUVW
26121,202441369349301334,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,2023,FULCRUM FOUNDATION,710 9TH AVE,SEATTLE,WA,98104.0,161616262.0,...,NaN,NaN,NaN,NaN,NaN,S50,S,T20,T,RSTUVW
462902,202410469349300741,810739440,AMERICAN ONLINE GIVING FOUNDATION INC,2023,INDIVIDUALS STANDING AGAINST INTERPERSONAL VIO...,258 ALLSTON ST UNIT C,BRIGHTON,MA,2135.0,853529545.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,W03,W,RSTUVW
51674,202441369349301334,110303001,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,2023,COMMUNITY FORKLIFT,4671 TANGLEWOOD DR,EDMONSTON,MD,20781.0,521975012.0,...,NaN,NaN,NaN,NaN,NaN,S50,S,S21,S,RSTUVW
108783,202430719349300413,203142622,LUTHERAN LEGACY FOUNDATION INC,2023,PEACE LUTHERAN SCHOOL ENDOW ASSOC,300 LINCOLN STREET,ANTIGO,WI,54409.0,391474294.0,...,NaN,NaN,NaN,NaN,NaN,T31,T,T12,T,RSTUVW
128425,202441359349309439,232888152,VANGUARD CHARITABLE ENDOWMENT PROGRAM,2023,HEARTLAND INSTITUTE,3939 N WILKE RD,ARLINGTON HEIGHTS,IL,60004.0,363309812.0,...,NaN,NaN,NaN,NaN,NaN,T700,T,W20G,W,RSTUVW
136278,202441359349309439,232888152,VANGUARD CHARITABLE ENDOWMENT PROGRAM,2023,SIDEKICK FOUNDATION INC,4000 WEST 106TH ST 125-238,CARMEL,IN,46032.0,453996413.0,...,NaN,NaN,NaN,NaN,NaN,T700,T,T30,T,RSTUVW
514513,202421349349305987,952942582,THE SAN DIEGO FOUNDATION,2023,ONEOC,1901 E 4TH ST STE 100,SANTA ANA,CA,92705.0,952021700.0,...,NaN,NaN,NaN,NaN,NaN,T31,T,T40Z,T,RSTUVW
219805,202411039349301716,311640316,SCHWAB CHARITABLE FUND,2023,RSM BOSTON FOUNDATION INC,80 CITY SQUARE,BOSTON,MA,21290000.0,464101902.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,T21,T,RSTUVW
95268,202443179349309079,133062214,THE NEW YORK COMMUNITY TRUST,2023,UNITED WAY OF WESTCHESTER AND PUTNAM INC,336 CENTRAL PARK AVENUE,WHITE PLAINS,NY,106061500.0,131997636.0,...,NaN,NaN,NaN,NaN,NaN,T31,T,T70Z,T,RSTUVW
91237,202421169349301122,113813663,THE GOLDMAN SACHS CHARITABLE GIFT FUND,2023,ROBIN HOOD FOUNDATION,826 BROADWAY FL 9,NEW YORK,NY,10003.0,133441066.0,...,NaN,NaN,NaN,NaN,NaN,T30,T,T700,T,RSTUVW
510840,202441149349301229,943192688,KAZAN MCCLAIN PARTNERS' FOUNDATION,2023,KING RIDGE FOUNDATION,PO BOX 5873,SANTA ROSA,CA,95402.0,270420906.0,...,NaN,NaN,NaN,NaN,NaN,T90,T,T31,T,RSTUVW

### Output results

In [ ]:
# Output the alldaf grants files

full_output_df = alldaf_allntee_df.copy()
full_output_df.to_csv(full_output_path, index=False)

nod2d_output_df = alldaf_filtered_df.copy()
nod2d_output_df.to_csv(nod2doutput_path, index=False)

In [150]:
# Output the summary tables

grantor_summary_df = grantor_summary_combined.copy()
grantor_summary_df.to_csv(grantor_summary_path, index=False)

recipient_summary_df = recipient_summary_combined.copy()
recipient_summary_df.to_csv(recipient_summary_path, index=False)

shonni_summary_path = os.path.join(output_directory, "Shonni_summary.csv")
shonni_combined.to_csv(shonni_summary_path, index=False)

socben_summary_path = os.path.join(output_directory, "societal_benefit_sample_orgs.csv")
socben_sample.to_csv(socben_summary_path, index=False)