### Load packages

In [2]:
import pandas as pd
import os
import numpy as np
from datetime import datetime

### Define parameters and file info

In [3]:
# -----------------------------------------------------------------------
# Directory info
# -----------------------------------------------------------------------

github_data_directory = r"..\data\nonprofit_economy"
area990_data_directory = r"..\..\..\Documents\Work\IPS\Area 990\Data Sources\Nonprofits\csvs"

ntee_directory = r"..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV"

output_directory = r"..\data\nonprofit_economy"

# -----------------------------------------------------------------------
# DAF-to-DAF data
# -----------------------------------------------------------------------

basic_file = r"c3s_0_i_viii_29mo_2023_20260603_095807.csv"
basic_path = os.path.join(area990_data_directory, basic_file)
print(
    "Basic CSV file:",
    basic_path,
    "EXISTS" if os.path.exists(basic_path) else "MISSING"
)

# -----------------------------------------------------------------------
# Output files
# -----------------------------------------------------------------------

revenue_summary_file = r"basic_revenue_summary_by_org_NTEE"
revenue_summary_path = os.path.join(output_directory, revenue_summary_file + ".csv")
print("Revenue Summary file:", revenue_summary_path)

Basic CSV file: ..\..\..\Documents\Work\IPS\Area 990\Data Sources\Nonprofits\csvs\c3s_0_i_viii_29mo_2023_20260603_095807.csv EXISTS
Revenue Summary file: ..\data\nonprofit_economy\basic_revenue_summary_by_org_NTEE.csv

### Load in data

In [4]:
# Load DAF basic data

basic_raw_df = pd.read_csv(basic_path)

basic_raw_df.head()

,Object ID,EIN,Name,Year of Tax Period End Date,Month of Tax Period End Date,BMF Subsection Code,NTEE_COMBINED,501c3 Indicator,Total Grants CY,Total Expenses CY,...,part_viii_InvstmntIncm_ExclsnAmt,part_viii_InvstmntIncm_RltdOrExmptFncIncmAmt,Total investment income,part_viii_InvstmntIncm_UnrltdBsnssRvnAmt,Membership Dues,Noncash Contributions,Net gain or loss from investments,Related Organizations,Total Contributions,Total Non-Government Contributions Received
0,202421369349305437,10024645,BANGOR SYMPHONY ORCHESTRA,2023,June,3.0,A69,False,0.0,1004403.0,...,49532.0,NaN,49532.0,NaN,NaN,NaN,-48380.0,NaN,432835.0,432835
1,202401299349304210,10085716,HANCOCK COUNTY AGRICULTURAL SOCIETY,2023,December,3.0,N52,False,0.0,517796.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,202431319349304643,10130427,BRIDGTON HOSPITAL,2023,June,3.0,E220,False,0.0,54554893.0,...,378989.0,NaN,378989.0,NaN,NaN,NaN,-172302.0,NaN,6846662.0,4090874
3,202403179349306720,10133442,OXFORD COUNTY AGRICULTURAL SOCIETY,2023,December,3.0,Z99,False,0.0,411510.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,116935.0,116935
4,202423059349300717,10145133,PROUTS NECK ASSOCIATION,2023,December,3.0,NaN,False,16338.0,151135.0,...,24954.0,NaN,24954.0,NaN,NaN,NaN,NaN,NaN,265711.0,265711

### Clean and format columns

In [5]:
basic_raw_df.columns

Index(['Object ID', 'EIN', 'Name', 'Year of Tax Period End Date',
       'Month of Tax Period End Date', 'BMF Subsection Code', 'NTEE_COMBINED',
       '501c3 Indicator', 'Total Grants CY', 'Total Expenses CY',
       'Total Revenue CY', 'Net Assets or Fund Balances EOY',
       'part_i_NtUnrltdBsTxblIncmAmt', 'Total Assets EOY',
       'part_i_TtlEmplyCnt', 'part_i_VtngMmbrsGvrnngBdyCnt',
       'part_i_VtngMmbrsIndpndntCnt', 'All Other Contributions',
       'Federated Campaigns', 'Fundraising Events', 'Government Grants',
       'part_viii_InvstmntIncm_ExclsnAmt',
       'part_viii_InvstmntIncm_RltdOrExmptFncIncmAmt',
       'Total investment income', 'part_viii_InvstmntIncm_UnrltdBsnssRvnAmt',
       'Membership Dues', 'Noncash Contributions',
       'Net gain or loss from investments', 'Related Organizations',
       'Total Contributions', 'Total Non-Government Contributions Received'],
      dtype='object')

In [6]:
# Clean & format columns in basic data

basic_clean_df = basic_raw_df.copy()

# Rename EIN columns
# basic_clean_df.rename(
#     columns={"DnrAdvsdFndsCntrAmt": "Contributions to DAFs", "DnrAdvsdFndsGrntsAmt": "Grants from DAFs"},
#     inplace=True
# )

# Convert integer columns to integer format
int_cols = ["EIN"]
basic_clean_df[int_cols] = basic_clean_df[int_cols].astype("Int64")

# Convert revenue columns to float
basic_clean_df["Total Non-Government Contributions Received"] = basic_clean_df["Total Non-Government Contributions Received"].astype(float)
basic_clean_df["Government Grants"] = basic_clean_df["Government Grants"].astype(float)

basic_clean_df.head()

,Object ID,EIN,Name,Year of Tax Period End Date,Month of Tax Period End Date,BMF Subsection Code,NTEE_COMBINED,501c3 Indicator,Total Grants CY,Total Expenses CY,...,part_viii_InvstmntIncm_ExclsnAmt,part_viii_InvstmntIncm_RltdOrExmptFncIncmAmt,Total investment income,part_viii_InvstmntIncm_UnrltdBsnssRvnAmt,Membership Dues,Noncash Contributions,Net gain or loss from investments,Related Organizations,Total Contributions,Total Non-Government Contributions Received
0,202421369349305437,10024645,BANGOR SYMPHONY ORCHESTRA,2023,June,3.0,A69,False,0.0,1004403.0,...,49532.0,NaN,49532.0,NaN,NaN,NaN,-48380.0,NaN,432835.0,432835.0
1,202401299349304210,10085716,HANCOCK COUNTY AGRICULTURAL SOCIETY,2023,December,3.0,N52,False,0.0,517796.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,202431319349304643,10130427,BRIDGTON HOSPITAL,2023,June,3.0,E220,False,0.0,54554893.0,...,378989.0,NaN,378989.0,NaN,NaN,NaN,-172302.0,NaN,6846662.0,4090874.0
3,202403179349306720,10133442,OXFORD COUNTY AGRICULTURAL SOCIETY,2023,December,3.0,Z99,False,0.0,411510.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,116935.0,116935.0
4,202423059349300717,10145133,PROUTS NECK ASSOCIATION,2023,December,3.0,NaN,False,16338.0,151135.0,...,24954.0,NaN,24954.0,NaN,NaN,NaN,NaN,NaN,265711.0,265711.0

### Create summaries by NTEE code

In [7]:
# Function to calculate Shonni's summary groupings on 

def shonni_groups(row, first_digit_ntee_code, full_ntee_code):

    code = row[first_digit_ntee_code]
    combined = str(row[full_ntee_code]).upper() if pd.notna(row[full_ntee_code]) else ""
    
    if pd.isna(code):
        return None
    
    code = str(code).upper()

    if combined.startswith(("T30", "T31", "T32")): # private foundations, community foundations, and corporate foundations
        return "Foundations"
    
    if code == "A":
        return "Arts, Culture, Humanities"
    
    elif code == "B":
        if combined.startswith(("B40", "B41", "B43", "B50")):
            return "Colleges and Universities"
        else:
            return "Other Education"
    
    elif code in ["C", "D"]:
        return "Environment and Animals"
    
    elif code in ["E", "F", "G", "H"]:
        if combined.startswith(("E20", "E21", "E22", "E24", "E90", "E91", "E92")):
            return "Hospitals and Nursing Homes"
        else:
            return "Other Health"
    
    elif code in ["I", "J", "K", "L", "M", "N", "O", "P"]:
        return "Human Services"
    
    elif code == "Q":
        return "International, Foreign Affairs"
    
    elif code in ["R", "S", "T", "U", "V", "W"]:
        return "Public, Societal Benefit"
    
    elif code == "X":
        return "Religion Related"
    

    elif code in ["Y", "Z"]:
        return "Unknown, Unclassified"
    
    else:
        return None

In [9]:
# Apply Shonni groupings to basic revenue by NTEE code

basic_grouped_df = basic_clean_df.copy()

# Create one-digit NTEE code columm
basic_grouped_df["NTEE_FIRST_DIGIT"] = basic_grouped_df["NTEE_COMBINED"].str[0]

basic_grouped_df["NTEE_ACTIVITY"] = basic_grouped_df.apply(
    shonni_groups,
    axis=1,
    args=("NTEE_FIRST_DIGIT", "NTEE_COMBINED")
)

basic_grouped_df.head()

,Object ID,EIN,Name,Year of Tax Period End Date,Month of Tax Period End Date,BMF Subsection Code,NTEE_COMBINED,501c3 Indicator,Total Grants CY,Total Expenses CY,...,Total investment income,part_viii_InvstmntIncm_UnrltdBsnssRvnAmt,Membership Dues,Noncash Contributions,Net gain or loss from investments,Related Organizations,Total Contributions,Total Non-Government Contributions Received,NTEE_FIRST_DIGIT,NTEE_ACTIVITY
0,202421369349305437,10024645,BANGOR SYMPHONY ORCHESTRA,2023,June,3.0,A69,False,0.0,1004403.0,...,49532.0,NaN,NaN,NaN,-48380.0,NaN,432835.0,432835.0,A,"Arts, Culture, Humanities"
1,202401299349304210,10085716,HANCOCK COUNTY AGRICULTURAL SOCIETY,2023,December,3.0,N52,False,0.0,517796.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,N,Human Services
2,202431319349304643,10130427,BRIDGTON HOSPITAL,2023,June,3.0,E220,False,0.0,54554893.0,...,378989.0,NaN,NaN,NaN,-172302.0,NaN,6846662.0,4090874.0,E,Hospitals and Nursing Homes
3,202403179349306720,10133442,OXFORD COUNTY AGRICULTURAL SOCIETY,2023,December,3.0,Z99,False,0.0,411510.0,...,1.0,NaN,NaN,NaN,NaN,NaN,116935.0,116935.0,Z,"Unknown, Unclassified"
4,202423059349300717,10145133,PROUTS NECK ASSOCIATION,2023,December,3.0,NaN,False,16338.0,151135.0,...,24954.0,NaN,NaN,NaN,NaN,NaN,265711.0,265711.0,NaN,None

In [10]:
# Define activity area sort order

activity_order = ["Arts, Culture, Humanities", "Other Education", "Colleges and Universities", "Environment and Animals", "Other Health", 
         "Hospitals and Nursing Homes", "Human Services", "International, Foreign Affairs", "Public, Societal Benefit",
         "Foundations", "Religion Related", "Unknown, Unclassified"]

In [13]:
# Create summary of basic data

basic_summary_df = basic_grouped_df.copy()

basic_summary_df["NTEE_ACTIVITY"] = basic_summary_df.apply(
    shonni_groups,
    axis=1,
    args=("NTEE_FIRST_DIGIT", "NTEE_COMBINED")
)

basic_summary = (
    basic_summary_df
    .groupby("NTEE_ACTIVITY", as_index=False)
    .agg(
        num_orgs=("EIN", "count"),
        nongovt_contribs=("Total Non-Government Contributions Received", "sum"),
        govt_grants=("Government Grants", "sum"),
    )
)

basic_summary["NTEE_ACTIVITY"] = pd.Categorical(
    basic_summary["NTEE_ACTIVITY"],
    categories=activity_order,
    ordered=True
)

basic_summary = basic_summary.sort_values("NTEE_ACTIVITY")

basic_summary

                     NTEE_ACTIVITY  num_orgs  nongovt_contribs   govt_grants
0        Arts, Culture, Humanities     20956      2.111428e+10  7.575421e+09
7                  Other Education     33899      5.144907e+10  4.671118e+10
1        Colleges and Universities      1709      2.820172e+10  2.769968e+10
2          Environment and Animals     12724      1.829038e+10  4.433741e+09
8                     Other Health     21764      4.078055e+10  3.628373e+10
4      Hospitals and Nursing Homes      5514      2.836411e+10  1.655540e+10
5                   Human Services     79729      6.911355e+10  7.615999e+10
6   International, Foreign Affairs      5847      3.465556e+10  1.420670e+10
9         Public, Societal Benefit     21498      6.837925e+10  3.164523e+10
3                      Foundations      4877      4.167072e+10  8.876813e+08
10                Religion Related     12941      1.625898e+10  6.788184e+08
11           Unknown, Unclassified      2257      2.021496e+09  1.944196e+09

### Output results

In [14]:
# Output the recipient summary table to csv

# Archive old output file if present

if os.path.exists(revenue_summary_path):

    # Get modification time of existing file
    old_timestamp = datetime.fromtimestamp(
        os.path.getmtime(revenue_summary_path)
    ).strftime("%Y%m%d_%H%M%S")

    archived_filename = (
        f"{revenue_summary_file}_archived_{old_timestamp}.csv"
    )

    archived_path = os.path.join(
        output_directory,
        archived_filename
    )

    os.rename(
        revenue_summary_path,
        archived_path
    )

    print(
        "Archived existing file:",
        archived_path
    )

basic_summary.to_csv(revenue_summary_path, index=False)

Archived existing file: ..\data\nonprofit_economy\basic_revenue_summary_by_org_NTEE_archived_20260701_155045.csv