### Load packages

In [135]:
import pandas as pd
import os
import numpy as np
from datetime import datetime

### Define parameters and file info

In [163]:
# -----------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------

use_bmf = False

# -----------------------------------------------------------------------
# Directory info
# -----------------------------------------------------------------------

github_data_directory = r"..\data\nonprofit_economy"
area990_data_directory = r"..\..\..\Documents\Work\IPS\Area 990\Data Sources\DAFs\csvs"

bmf_directory = r"..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\EO BMF Files"
ntee_directory = r"..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV"

output_directory = r"..\data\nonprofit_economy"

# -----------------------------------------------------------------------
# DAF-to-DAF data
# -----------------------------------------------------------------------

daf2daf_file = r"daf_to_daf_grants_2023.csv"
daf2daf_path = os.path.join(area990_data_directory, daf2daf_file)
print(
    "DAF-to-DAF grants CSV file:",
    daf2daf_path,
    "EXISTS" if os.path.exists(daf2daf_path) else "MISSING"
)

# -----------------------------------------------------------------------
# All-DAF data
# -----------------------------------------------------------------------
alldaf_file = r"alldafs_grants_29mo_2023.csv"
alldaf_path = os.path.join(area990_data_directory, alldaf_file)
print(
    "All DAF grants CSV file:",
    daf2daf_path,
    "EXISTS" if os.path.exists(daf2daf_path) else "MISSING"
)

# -----------------------------------------------------------------------
# BMF data
# -----------------------------------------------------------------------

bmf_file = r"UNIFIED_BMF_V1.2"
bmf_path = os.path.join(bmf_directory, bmf_file + ".csv")
print(
    "BMF file:",
    bmf_path,
    "EXISTS" if os.path.exists(daf2daf_path) else "MISSING"
)

# -----------------------------------------------------------------------
# NTEE data
# -----------------------------------------------------------------------

ntee_file = r"eo_bmf_extract_narrow"
ntee_path = os.path.join(ntee_directory, ntee_file + ".csv")
print(
    "NTEE file:",
    ntee_path,
    "EXISTS" if os.path.exists(ntee_path) else "MISSING"
)

# -----------------------------------------------------------------------
# Output files
# -----------------------------------------------------------------------

recipient_summary_file = r"DAF_grants_summary_by_recipient_NTEE"
recipient_summary_path = os.path.join(output_directory, recipient_summary_file + ".csv")
print("Recipient Summary file:", recipient_summary_path)

DAF-to-DAF grants CSV file: ..\..\..\Documents\Work\IPS\Area 990\Data Sources\DAFs\csvs\daf_to_daf_grants_2023.csv EXISTS
All DAF grants CSV file: ..\..\..\Documents\Work\IPS\Area 990\Data Sources\DAFs\csvs\daf_to_daf_grants_2023.csv EXISTS
BMF file: ..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\EO BMF Files\UNIFIED_BMF_V1.2.csv EXISTS
NTEE file: ..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\eo_bmf_extract_narrow.csv EXISTS
Recipient Summary file: ..\data\nonprofit_economy\DAF_grants_summary_by_recipient_NTEE.csv

### Load in data

In [137]:
# Load DAF-to-DAF data

daf2daf_raw_df = pd.read_csv(daf2daf_path)

daf2daf_raw_df.head()

,EIN,RcpntTbl_RcpntEIN,Year of Tax Period End Date,Organization Name,Recipient Name,Number of DAF Grants,Total DAF Grants
0,10782573,110303001.0,2023,ADVISORS CHARITABLE GIFT FUND,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,1,204922.0
1,10782573,352129262.0,2023,ADVISORS CHARITABLE GIFT FUND,RENAISSANCE CHARITABLE FOUNDATION,1,455168.0
2,10782573,527082731.0,2023,ADVISORS CHARITABLE GIFT FUND,MORGAN STANLEY GLOBAL IMPACT FUNDING TRUST INC,1,220194.0
3,10782573,593652538.0,2023,ADVISORS CHARITABLE GIFT FUND,RAYMOND JAMES CHARITABLE ENDOWMENT FUND,1,254975.0
4,20714460,110303001.0,2023,EDEN BRIDGE FOUNDATION,FIDELITY CHARITABLE,1,70500.0

In [138]:
# Load All-DAF data

alldaf_raw_df = pd.read_csv(alldaf_path)

alldaf_raw_df.head()

C:\Users\hefla\AppData\Local\Temp\ipykernel_45972\3935524124.py:3: DtypeWarning: Columns (13,14,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  alldaf_raw_df = pd.read_csv(alldaf_path)

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntTbl_VltnMthdUsdDsc,RcpntTbl_NnCshAssstncDsc,USAddrss_AddrssLn2Txt,RcpntTbl_NnCshAssstncAmt,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
# Load BMF data

if use_bmf:
    bmf_raw_df = pd.read_csv(bmf_path)
    print(bmf_raw_df.info())
    bmf_raw_df.head()

In [140]:
# Load in NTEE data

ntee_raw_df = pd.read_csv(ntee_path)

ntee_raw_df.head()

,EIN,LAST_YEAR_IN_BMF,ORG_NAME_RAW,SUBSECTION_CODE,ORG_ADDR_STATE,NTEE_IRS,NTEE_OLD_BMF,NTEE_CODE_RAW,NTEE_CODE_CLEAN,NTEE_COMBINED,NTEE_SOURCE
0,4,2001.0,SCRIPT INC,3.0,OH,NaN,B90,B90,B90,B90,NCCS_CLEAN
1,5,2004.0,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3.0,GA,NaN,A50,A50,A50,A50,NCCS_CLEAN
2,3154,2016.0,OAKLEAF FOREST TENANT MANAGEMENT,3.0,VA,NaN,C36,C36,C36,C36,NCCS_CLEAN
3,4101,2023.0,SOUTH LAFOURCHE QUARTERBACK CLUB,3.0,LA,NaN,N65,N65,N65,N65,NCCS_CLEAN
4,4882,2004.0,LITTLE LEAGUE BASEBALL INC,3.0,MD,NaN,N63,N63,N63,N63,NCCS_CLEAN

### Clean and format columns

In [141]:
daf2daf_raw_df.columns

Index(['EIN', 'RcpntTbl_RcpntEIN', 'Year of Tax Period End Date',
       'Organization Name', 'Recipient Name', 'Number of DAF Grants',
       'Total DAF Grants'],
      dtype='object')

In [142]:
# Clean & format columns in DAF2DAF data

daf2daf_clean_df = daf2daf_raw_df.copy()

# Rename EIN columns
daf2daf_clean_df.rename(
    columns={"EIN": "Grantor EIN", "RcpntTbl_RcpntEIN": "Recipient EIN", "Total DAF Grants": "Grant Amount"},
    inplace=True
)

# Convert integer columns to integer format
int_cols = ["Grantor EIN", "Recipient EIN"]
daf2daf_clean_df[int_cols] = daf2daf_clean_df[int_cols].astype("Int64")

# Convert grant amount to float
daf2daf_clean_df["Grant Amount"] = daf2daf_clean_df["Grant Amount"].astype(float)

daf2daf_clean_df.head()

,Grantor EIN,Recipient EIN,Year of Tax Period End Date,Organization Name,Recipient Name,Number of DAF Grants,Grant Amount
0,10782573,110303001,2023,ADVISORS CHARITABLE GIFT FUND,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,1,204922.0
1,10782573,352129262,2023,ADVISORS CHARITABLE GIFT FUND,RENAISSANCE CHARITABLE FOUNDATION,1,455168.0
2,10782573,527082731,2023,ADVISORS CHARITABLE GIFT FUND,MORGAN STANLEY GLOBAL IMPACT FUNDING TRUST INC,1,220194.0
3,10782573,593652538,2023,ADVISORS CHARITABLE GIFT FUND,RAYMOND JAMES CHARITABLE ENDOWMENT FUND,1,254975.0
4,20714460,110303001,2023,EDEN BRIDGE FOUNDATION,FIDELITY CHARITABLE,1,70500.0

In [143]:
# Clean & format columns in All-DAF data

alldaf_clean_df = alldaf_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["Object ID", "EIN", "Year of Tax Period End Date", "RcpntTbl_RcpntEIN", "USAddrss_ZIPCd"]
alldaf_raw_df[int_cols] = alldaf_raw_df[int_cols].astype("Int64")

# Clean up dollar formatting in CSV file
dollar_cols = ["RcpntTbl_CshGrntAmt", "RcpntTbl_NnCshAssstncAmt"]
# Convert to float
alldaf_clean_df[dollar_cols] = alldaf_clean_df[dollar_cols].astype(float)

alldaf_clean_df.head()

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntTbl_VltnMthdUsdDsc,RcpntTbl_NnCshAssstncDsc,USAddrss_AddrssLn2Txt,RcpntTbl_NnCshAssstncAmt,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

### Clean, format, and filter columns in BMF data

In [144]:
# Filter BMF rows to only those where the ORG_YEAR_LAST is no earlier than the earliest year we want

if use_bmf:
    earliest_year = 0
    print("Before filtering:", len(bmf_raw_df))
    bmf_filtered_df = bmf_raw_df[bmf_raw_df["ORG_YEAR_LAST"] >= earliest_year]
    print("After filtering:", len(bmf_filtered_df))

In [145]:
# QC BMF versus NCCS codes

if use_bmf:
    # Function to get first letter of a column's values
    # def get_first_letter(series):
    #     return series.astype(str).str[0].where(series.notna(), None)
    def get_first_letter(series):
        return series.astype(str).str[0]

    # Get counts

    # BMF counts
    bmf_nccs_counts = get_first_letter(bmf_filtered_df["NTEE_NCCS"]).value_counts()
    bmf_irs_counts  = get_first_letter(bmf_filtered_df["NTEE_IRS"]).value_counts()

    # NCCS counts
    nccs_nccs_counts = get_first_letter(ntee_raw_df["NTEE_NCCS"]).value_counts()
    nccs_irs_counts  = get_first_letter(ntee_raw_df["NTEE_IRS"]).value_counts()

    # Combine into a table
    comparison_df = pd.DataFrame({
        "bmf_NTEE_NCCS": bmf_nccs_counts,
        "bmf_NTEE_IRS":  bmf_irs_counts,
        "nccs_NTEE_NCCS": nccs_nccs_counts,
        "nccs_NTEE_IRS":  nccs_irs_counts
    }).fillna(0).astype(int)

    # Sort by letter
    comparison_df = comparison_df.sort_index()

    comparison_df

### Clean and format columns in NTEE data

In [146]:
ntee_raw_df.columns

Index(['EIN', 'LAST_YEAR_IN_BMF', 'ORG_NAME_RAW', 'SUBSECTION_CODE',
       'ORG_ADDR_STATE', 'NTEE_IRS', 'NTEE_OLD_BMF', 'NTEE_CODE_RAW',
       'NTEE_CODE_CLEAN', 'NTEE_COMBINED', 'NTEE_SOURCE'],
      dtype='object')

In [147]:
# Clean & format columns in NTEE data

ntee_clean_df = ntee_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["EIN", "SUBSECTION_CODE"]
ntee_clean_df[int_cols] = ntee_clean_df[int_cols].astype("Int64")

# Drop unnecessary columns
cols_to_drop = ["ORG_ADDR_STATE", "NTEE_OLD_BMF", "NTEE_IRS", "NTEE_CODE_RAW", "NTEE_CODE_CLEAN", "NTEE_SOURCE"]
ntee_clean_df = ntee_clean_df.drop(columns=cols_to_drop)

# Uppercase NTEE_COMBINED
ntee_clean_df["NTEE_COMBINED"] = ntee_clean_df["NTEE_COMBINED"].str.upper()

# Create one-digit NTEE code columm
ntee_clean_df["NTEE_FIRST_DIGIT"] = ntee_clean_df["NTEE_COMBINED"].str[0]

# Create two-digit NTEE code columm
ntee_clean_df["NTEE_FIRST_THREE_DIGITS"] = ntee_clean_df["NTEE_COMBINED"].str[:3]

# Identify invalid first digits (not A-Z or null/NaN) and replace with "0"
ntee_clean_df["NTEE_FIRST_DIGIT"] = ntee_clean_df["NTEE_FIRST_DIGIT"].mask(
    ntee_clean_df["NTEE_FIRST_DIGIT"].isna() | ~ntee_clean_df["NTEE_FIRST_DIGIT"].str.match(r"^[A-Z]$", na=False),
    "0"
)
ntee_clean_df["NTEE_FIRST_THREE_DIGITS"] = ntee_clean_df["NTEE_FIRST_THREE_DIGITS"].mask(
    ntee_clean_df["NTEE_FIRST_THREE_DIGITS"].isna()
    | ~ntee_clean_df["NTEE_FIRST_THREE_DIGITS"].str.match(r"^[A-Z][0-9][0-9]$", na=False),
    "0"
)

ntee_clean_df.head()

,EIN,LAST_YEAR_IN_BMF,ORG_NAME_RAW,SUBSECTION_CODE,NTEE_COMBINED,NTEE_FIRST_DIGIT,NTEE_FIRST_THREE_DIGITS
0,4,2001.0,SCRIPT INC,3,B90,B,B90
1,5,2004.0,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3,A50,A,A50
2,3154,2016.0,OAKLEAF FOREST TENANT MANAGEMENT,3,C36,C,C36
3,4101,2023.0,SOUTH LAFOURCHE QUARTERBACK CLUB,3,N65,N,N65
4,4882,2004.0,LITTLE LEAGUE BASEBALL INC,3,N63,N,N63

In [148]:
# Find records where NTEE_COMBINED is null or 0

# Rows where NTEE_FIRST_DIGIT is NaN or not A-Z
invalid_ntee_rows = ntee_clean_df[
    ntee_clean_df["NTEE_FIRST_DIGIT"].isna() |        # null/NaN
    ~ntee_clean_df["NTEE_FIRST_DIGIT"].str.match(r"^[A-Z]$", na=False)  # not a single uppercase letter
]

# print(invalid_ntee_rows.value_counts())
# Show the results
# print(invalid_ntee_rows)
print("Number of invalid NTEE codes:", len(invalid_ntee_rows))

Number of invalid NTEE codes: 64854

In [149]:
# Dedupe the NTEE file

ntee_valid_df = ntee_clean_df.copy()
print("Before deduping:", len(ntee_valid_df))

# Find rows with valid NTEE codes
ntee_valid_df["is_valid_ntee"] = (
    ntee_valid_df["NTEE_FIRST_DIGIT"]
    .astype(str)
    .str.match("^[A-Za-z]$")
)

# Make sure the year is numeric
ntee_valid_df["LAST_YEAR_IN_BMF"] = pd.to_numeric(ntee_valid_df["LAST_YEAR_IN_BMF"], errors="coerce")

# Sort by EIN, valid ntee code flag, and LAST_YEAR_IN_BMF
ntee_sorted_df = ntee_valid_df.sort_values(
    by=["EIN", "is_valid_ntee", "LAST_YEAR_IN_BMF"],
    ascending=[True, False, False]
)

# Keep only the first record for each EIN
ntee_dedupe_df = ntee_sorted_df.drop_duplicates(subset="EIN", keep="first")

# Drop the helper column
ntee_dedupe_df = ntee_dedupe_df.drop(columns=["is_valid_ntee"])

print("After deduping:", len(ntee_dedupe_df))

ntee_dedupe_df.head()

Before deduping: 3687435
After deduping: 3687435

,EIN,LAST_YEAR_IN_BMF,ORG_NAME_RAW,SUBSECTION_CODE,NTEE_COMBINED,NTEE_FIRST_DIGIT,NTEE_FIRST_THREE_DIGITS
0,4,2001.0,SCRIPT INC,3,B90,B,B90
1,5,2004.0,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3,A50,A,A50
2,3154,2016.0,OAKLEAF FOREST TENANT MANAGEMENT,3,C36,C,C36
3,4101,2023.0,SOUTH LAFOURCHE QUARTERBACK CLUB,3,N65,N,N65
4,4882,2004.0,LITTLE LEAGUE BASEBALL INC,3,N63,N,N63

In [150]:
# Check presence of duplicate rows
duplicates_df = ntee_dedupe_df[ntee_dedupe_df["EIN"].duplicated(keep=False)]

print(f"Total duplicate rows: {len(duplicates_df)}")
# duplicates_df.head(10)

Total duplicate rows: 0

### Add NTEE codes to All-DAF grants file

In [151]:
alldaf_clean_df.columns

Index(['Object ID', 'EIN', 'Organization Name', 'Year of Tax Period End Date',
       'RcpntBsnssNm_BsnssNmLn1Txt', 'USAddrss_AddrssLn1Txt', 'USAddrss_CtyNm',
       'USAddrss_SttAbbrvtnCd', 'USAddrss_ZIPCd', 'RcpntTbl_RcpntEIN',
       'RcpntTbl_IRCSctnDsc', 'RcpntTbl_CshGrntAmt', 'RcpntTbl_PrpsOfGrntTxt',
       'RcpntTbl_VltnMthdUsdDsc', 'RcpntTbl_NnCshAssstncDsc',
       'USAddrss_AddrssLn2Txt', 'RcpntTbl_NnCshAssstncAmt',
       'RcpntBsnssNm_BsnssNmLn2Txt', 'FrgnAddrss_AddrssLn1Txt',
       'FrgnAddrss_CtyNm', 'FrgnAddrss_CntryCd', 'FrgnAddrss_PrvncOrSttNm',
       'FrgnAddrss_FrgnPstlCd'],
      dtype='object')

In [152]:
# Add NTEE codes for grantors

print("Before merging:", len(alldaf_clean_df))
print(alldaf_clean_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_grantor_ntee_df = (
    alldaf_clean_df
    .merge(
        ntee_dedupe_df[["EIN", "NTEE_COMBINED", "NTEE_FIRST_DIGIT", "NTEE_FIRST_THREE_DIGITS"]],
        left_on=["EIN"],
        right_on=["EIN"],
        how="left",
        indicator=True
    )
)

# Drop helper columns
alldaf_grantor_ntee_df = alldaf_grantor_ntee_df.drop(columns=["_merge"])

# Rename columns
alldaf_grantor_ntee_df = alldaf_grantor_ntee_df.rename(
    columns={
        "NTEE_COMBINED": "GRANTOR_NTEE_COMBINED",
        "NTEE_FIRST_DIGIT": "GRANTOR_NTEE_FIRST_DIGIT",
        "NTEE_FIRST_THREE_DIGITS": "GRANTOR_NTEE_FIRST_THREE_DIGITS"
    }
)

print("After merging:", len(alldaf_grantor_ntee_df))
print(alldaf_grantor_ntee_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_grantor_ntee_df.head()

Before merging: 516861
62237597993.0
After merging: 516861
62237597993.0

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,RcpntTbl_NnCshAssstncAmt,RcpntBsnssNm_BsnssNmLn2Txt,FrgnAddrss_AddrssLn1Txt,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,GRANTOR_NTEE_FIRST_THREE_DIGITS
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,T31
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,T31
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,T31
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,T31
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,T31,T,T31

In [153]:
# Add NTEE codes for recipients

print("Before merging:", len(alldaf_grantor_ntee_df))

# Select only the relevant columns from ntee_dedupe_df
recipient_ntee_df = ntee_dedupe_df[["EIN", "NTEE_COMBINED", "NTEE_FIRST_DIGIT", "NTEE_FIRST_THREE_DIGITS"]].rename(
    columns={
        "EIN": "RECIPIENT_EIN",
        "NTEE_COMBINED": "RECIPIENT_NTEE_COMBINED",
        "NTEE_FIRST_DIGIT": "RECIPIENT_NTEE_FIRST_DIGIT",
        "NTEE_FIRST_THREE_DIGITS": "RECIPIENT_NTEE_FIRST_THREE_DIGITS"
    }
)

alldaf_allntee_df = alldaf_grantor_ntee_df.merge(
    recipient_ntee_df,
    left_on="RcpntTbl_RcpntEIN",
    right_on="RECIPIENT_EIN",
    how="left"
)

# Drop the merge helper columns
alldaf_allntee_df = alldaf_allntee_df.drop(columns=["RECIPIENT_EIN"])
alldaf_allntee_df = alldaf_allntee_df.drop(columns=["_merge"], errors="ignore")

print("After merging:", len(alldaf_allntee_df))
print(alldaf_allntee_df["RcpntTbl_CshGrntAmt"].sum())

alldaf_allntee_df.head()

Before merging: 516861
After merging: 516861
62237597993.0

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,GRANTOR_NTEE_FIRST_THREE_DIGITS,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_FIRST_THREE_DIGITS
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,NaN,T31,T,T31,A6E,A,0
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,NaN,T31,T,T31,C60,C,C60
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,NaN,T31,T,T31,L24,L,L24
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,NaN,T31,T,T31,C35,C,C35
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,NaN,T31,T,T31,A65,A,A65

### Remove DAF-to-DAF grants from All-DAF grants (for no DAF-to-DAF file)

In [154]:
# Remove DAF2DAF grants from All-DAF grants list

print("Before filtering:", len(alldaf_allntee_df))
print("Records in DAF2DAF list:", len(daf2daf_clean_df))

merged = (
    alldaf_allntee_df
    .merge(
        daf2daf_clean_df[["Grantor EIN", "Recipient EIN"]],
        left_on=["EIN", "RcpntTbl_RcpntEIN"],
        right_on=["Grantor EIN", "Recipient EIN"],
        how="left",
        indicator=True
    )
)

# Keep only rows that are NOT daf-to-daf grants
no_daf2daf_filtered_df = merged[merged["_merge"] == "left_only"].copy()

# Keep only rows that ARE daf-to-daf grants
daf2daf_filtered_df = merged[merged["_merge"] == "both"].copy()

# Drop helper columns
no_daf2daf_filtered_df = no_daf2daf_filtered_df.drop(columns=["Grantor EIN", "Recipient EIN", "_merge"])
daf2daf_filtered_df = daf2daf_filtered_df.drop(columns=["Grantor EIN", "Recipient EIN", "_merge"])

print("All non DAF2DAF:", len(no_daf2daf_filtered_df))
print("DAF2DAF only:", len(daf2daf_filtered_df))

print("Sanity check total:", len(no_daf2daf_filtered_df) + len(daf2daf_filtered_df))

no_daf2daf_filtered_df.head()

Before filtering: 516861
Records in DAF2DAF list: 1266
All non DAF2DAF: 515533
DAF2DAF only: 1328
Sanity check total: 516861

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,FrgnAddrss_CtyNm,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,GRANTOR_NTEE_FIRST_THREE_DIGITS,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_FIRST_THREE_DIGITS
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,NaN,T31,T,T31,A6E,A,0
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,NaN,T31,T,T31,C60,C,C60
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,NaN,T31,T,T31,L24,L,L24
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,NaN,T31,T,T31,C35,C,C35
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,NaN,T31,T,T31,A65,A,A65

### Create summaries by NTEE code

In [ ]:
# Function to calculate Shonni's summary groupings on 

def shonni_groups(row, first_digit_ntee_code, full_ntee_code):

    code = row[first_digit_ntee_code]
    combined = str(row[full_ntee_code]).upper() if pd.notna(row[full_ntee_code]) else ""
    
    if pd.isna(code):
        return None
    
    code = str(code).upper()

    if combined.startswith(("T30", "T31", "T32")): # private foundations, community foundations, and corporate foundations
        return "Foundations"
    
    if code == "A":
        return "Arts, Culture, Humanities"
    
    elif code == "B":
        if combined.startswith(("B40", "B41", "B43", "B50")):
            return "Colleges and Universities"
        else:
            return "Other Education"
    
    elif code in ["C", "D"]:
        return "Environment and Animals"
    
    elif code in ["E", "F", "G", "H"]:
        if combined.startswith(("E20", "E21", "E22", "E24", "E90", "E91", "E92")):
            return "Hospitals and Nursing Homes"
        else:
            return "Other Health"
    
    elif code in ["I", "J", "K", "L", "M", "N", "O", "P"]:
        return "Human Services"
    
    elif code == "Q":
        return "International, Foreign Affairs"
    
    elif code in ["R", "S", "T", "U", "V", "W"]:
        return "Public, Societal Benefit"
    
    elif code == "X":
        return "Religion Related"
    

    elif code in ["Y", "Z"]:
        return "Unknown, Unclassified"
    
    else:
        return None

In [156]:
daf2daf_filtered_df.columns

Index(['Object ID', 'EIN', 'Organization Name', 'Year of Tax Period End Date',
       'RcpntBsnssNm_BsnssNmLn1Txt', 'USAddrss_AddrssLn1Txt', 'USAddrss_CtyNm',
       'USAddrss_SttAbbrvtnCd', 'USAddrss_ZIPCd', 'RcpntTbl_RcpntEIN',
       'RcpntTbl_IRCSctnDsc', 'RcpntTbl_CshGrntAmt', 'RcpntTbl_PrpsOfGrntTxt',
       'RcpntTbl_VltnMthdUsdDsc', 'RcpntTbl_NnCshAssstncDsc',
       'USAddrss_AddrssLn2Txt', 'RcpntTbl_NnCshAssstncAmt',
       'RcpntBsnssNm_BsnssNmLn2Txt', 'FrgnAddrss_AddrssLn1Txt',
       'FrgnAddrss_CtyNm', 'FrgnAddrss_CntryCd', 'FrgnAddrss_PrvncOrSttNm',
       'FrgnAddrss_FrgnPstlCd', 'GRANTOR_NTEE_COMBINED',
       'GRANTOR_NTEE_FIRST_DIGIT', 'GRANTOR_NTEE_FIRST_THREE_DIGITS',
       'RECIPIENT_NTEE_COMBINED', 'RECIPIENT_NTEE_FIRST_DIGIT',
       'RECIPIENT_NTEE_FIRST_THREE_DIGITS'],
      dtype='object')

In [157]:
# Apply Shonni groupings to daf-to-daf grants by RECIPIENT NTEE code

d2d_recip_summary_df = daf2daf_filtered_df.copy()

d2d_recip_summary_df["NTEE_ACTIVITY"] = d2d_recip_summary_df.apply(
    shonni_groups,
    axis=1,
    args=("RECIPIENT_NTEE_FIRST_DIGIT", "RECIPIENT_NTEE_COMBINED")
)

d2d_recip_summary_df.head()

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,GRANTOR_NTEE_FIRST_THREE_DIGITS,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_FIRST_THREE_DIGITS,NTEE_ACTIVITY
3102,202430729349301758,10782573,ADVISORS CHARITABLE GIFT FUND,2023,RENAISSANCE CHARITABLE FOUNDATION,8910 PURDUE RD,INDIANAPOLIS,IN,46268.0,352129262.0,...,NaN,NaN,NaN,W12,W,W12,T12,T,T12,"Public, Societal Benefit"
3105,202430729349301758,10782573,ADVISORS CHARITABLE GIFT FUND,2023,RAYMOND JAMES CHARITABLE ENDOWMENT FUND,FBO 561737 PO BOX 23559,ST PETERSBURG,FL,33742.0,593652538.0,...,NaN,NaN,NaN,W12,W,W12,T30,T,T30,"Public, Societal Benefit"
3106,202430729349301758,10782573,ADVISORS CHARITABLE GIFT FUND,2023,MORGAN STANLEY GLOBAL IMPACT FUNDING TRUST INC,28 STATE STREET 25TH FLOOR,BOSTON,MA,2109.0,527082731.0,...,NaN,NaN,NaN,W12,W,W12,T90,T,T90,"Public, Societal Benefit"
3107,202430729349301758,10782573,ADVISORS CHARITABLE GIFT FUND,2023,FIDELITY INVESTMENTS CHARITABLE GIFT FUND,100 CROSBY PARKWAY MAIL ZONE,COVINGTON,KY,41015.0,110303001.0,...,NaN,NaN,NaN,W12,W,W12,S50,S,S50,"Public, Societal Benefit"
3528,202401369349312450,20714460,EDEN BRIDGE FOUNDATION,2023,DONORSTRUST,1800 DIAGONAL ROAD SUITE 280,ALEXANDRIA,VA,22314.0,522166327.0,...,NaN,NaN,NaN,T20,T,T20,T99,T,T99,"Public, Societal Benefit"

In [158]:
# Apply Shonni groupings to daf-to-daf grants by RECIPIENT NTEE code

no_d2d_recip_summary_df = no_daf2daf_filtered_df.copy()

no_d2d_recip_summary_df["NTEE_ACTIVITY"] = no_d2d_recip_summary_df.apply(
    shonni_groups,
    axis=1,
    args=("RECIPIENT_NTEE_FIRST_DIGIT", "RECIPIENT_NTEE_COMBINED")
)

no_d2d_recip_summary_df.head()

,Object ID,EIN,Organization Name,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,USAddrss_AddrssLn1Txt,USAddrss_CtyNm,USAddrss_SttAbbrvtnCd,USAddrss_ZIPCd,RcpntTbl_RcpntEIN,...,FrgnAddrss_CntryCd,FrgnAddrss_PrvncOrSttNm,FrgnAddrss_FrgnPstlCd,GRANTOR_NTEE_COMBINED,GRANTOR_NTEE_FIRST_DIGIT,GRANTOR_NTEE_FIRST_THREE_DIGITS,RECIPIENT_NTEE_COMBINED,RECIPIENT_NTEE_FIRST_DIGIT,RECIPIENT_NTEE_FIRST_THREE_DIGITS,NTEE_ACTIVITY
0,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,317 MAIN ST COMMUNITY MUSIC CENTER INC,317 MAIN STREET,YARMOUTH,ME,4096.0,201424631.0,...,NaN,NaN,NaN,T31,T,T31,A6E,A,0,"Arts, Culture, Humanities"
1,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,350VERMONT,239 SOUTH UNION STREET SUITE 3,BURLINGTON,VT,5401.0,463647561.0,...,NaN,NaN,NaN,T31,T,T31,C60,C,C60,Environment and Animals
2,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,3I HOUSING OF MAINE,4 UNION PARK SUITE 3I,TOPSHAM,ME,4086.0,852568325.0,...,NaN,NaN,NaN,T31,T,T31,L24,L,L24,Human Services
3,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A CLIMATE TO THRIVE,PO BOX 75,MOUNT DESERT,ME,4660.0,810836597.0,...,NaN,NaN,NaN,T31,T,T31,C35,C,C35,Environment and Animals
4,202423099349303012,10391479,MAINE COMMUNITY FOUNDATION INC,2023,A COMPANY OF GIRLS,PO BOX 7527,PORTLAND,ME,4112.0,50631726.0,...,NaN,NaN,NaN,T31,T,T31,A65,A,A65,"Arts, Culture, Humanities"

In [ ]:
# Define activity area sort order

activity_order = ["Arts, Culture, Humanities", "Other Education", "Colleges and Universities", "Environment and Animals", "Other Health", 
         "Hospitals and Nursing Homes", "Human Services", "International, Foreign Affairs", "Public, Societal Benefit",
         "Foundations", "Religion Related", "Unknown, Unclassified"]

In [160]:
# Create summary of daf-to-daf data

d2d_recip_summary_df = daf2daf_filtered_df.copy()

d2d_recip_summary_df["NTEE_ACTIVITY"] = d2d_recip_summary_df.apply(
    shonni_groups,
    axis=1,
    args=("RECIPIENT_NTEE_FIRST_DIGIT", "RECIPIENT_NTEE_COMBINED")
)

d2d_recip_summary = (
    d2d_recip_summary_df
    .groupby("NTEE_ACTIVITY", as_index=False)
    .agg(
        Count_of_Grants=("RcpntTbl_CshGrntAmt", "count"),
        Grant_Amount=("RcpntTbl_CshGrntAmt", "sum")
    )
)

d2d_recip_summary["NTEE_ACTIVITY"] = pd.Categorical(
    d2d_recip_summary["NTEE_ACTIVITY"],
    categories=activity_order,
    ordered=True
)

d2d_recip_summary = d2d_recip_summary.sort_values("NTEE_ACTIVITY")

d2d_recip_summary

                    NTEE_ACTIVITY  Count_of_Grants  Grant_Amount
0       Arts, Culture, Humanities                2  2.230000e+04
5                 Other Education               31  3.958382e+07
1       Colleges and Universities                5  3.276660e+05
6                    Other Health               12  3.721920e+05
2     Hospitals and Nursing Homes                2  1.350000e+04
3                  Human Services               51  1.346308e+07
4  International, Foreign Affairs               25  4.193049e+06
7        Public, Societal Benefit             1136  3.925731e+09
8                Religion Related               64  1.118393e+08

In [161]:
# Create summary of no-daf-to-daf data

no_d2d_recip_summary_df = no_daf2daf_filtered_df.copy()

no_d2d_recip_summary_df["NTEE_ACTIVITY"] = no_d2d_recip_summary_df.apply(
    shonni_groups,
    axis=1,
    args=("RECIPIENT_NTEE_FIRST_DIGIT", "RECIPIENT_NTEE_COMBINED")
)

no_d2d_recip_summary = (
    no_d2d_recip_summary_df
    .groupby("NTEE_ACTIVITY", as_index=False)
    .agg(
        Count_of_Grants=("RcpntTbl_CshGrntAmt", "count"),
        Grant_Amount=("RcpntTbl_CshGrntAmt", "sum")
    )
)

no_d2d_recip_summary["NTEE_ACTIVITY"] = pd.Categorical(
    no_d2d_recip_summary["NTEE_ACTIVITY"],
    categories=activity_order,
    ordered=True
)

no_d2d_recip_summary = no_d2d_recip_summary.sort_values("NTEE_ACTIVITY")

no_d2d_recip_summary

                     NTEE_ACTIVITY  Count_of_Grants  Grant_Amount
0        Arts, Culture, Humanities            40462  2.905338e+09
6                  Other Education            64692  6.987960e+09
1        Colleges and Universities            11542  5.704186e+09
2          Environment and Animals            33254  2.766863e+09
7                     Other Health            36035  3.172545e+09
3      Hospitals and Nursing Homes             5998  2.282546e+09
4                   Human Services           114785  8.401092e+09
5   International, Foreign Affairs            19062  2.761109e+09
8         Public, Societal Benefit            51014  9.097285e+09
9                 Religion Related            70673  4.811374e+09
10           Unknown, Unclassified             4136  4.295551e+08

In [162]:
# Merge the no-daf-to-daf and the daf-to-daf data together into one summary table by RECIPIENT NTEE code

# Rename the columns in each summary dataframe
d2d_summary = d2d_recip_summary.rename(columns={
    "Count_of_Grants": "Count_D2D",
    "Grant_Amount": "Grant_Amount_D2D"
})

no_d2d_summary = no_d2d_recip_summary.rename(columns={
    "Count_of_Grants": "Count_No_D2D",
    "Grant_Amount": "Grant_Amount_No_D2D"
})

# Merge the two

combined_recipient_summary = d2d_summary.merge(
    no_d2d_summary,
    on="NTEE_ACTIVITY",
    how="outer"
)

# Fill any NaN numeric records with 0
combined_recipient_summary[[
    "Count_D2D",
    "Grant_Amount_D2D",
    "Count_No_D2D",
    "Grant_Amount_No_D2D"
]] = combined_recipient_summary[[
    "Count_D2D",
    "Grant_Amount_D2D",
    "Count_No_D2D",
    "Grant_Amount_No_D2D"
]].fillna(0)

combined_recipient_summary

,NTEE_ACTIVITY,Count_D2D,Grant_Amount_D2D,Count_No_D2D,Grant_Amount_No_D2D
0,"Arts, Culture, Humanities",2.0,2.230000e+04,40462,2.905338e+09
1,Other Education,31.0,3.958382e+07,64692,6.987960e+09
2,Colleges and Universities,5.0,3.276660e+05,11542,5.704186e+09
3,Environment and Animals,0.0,0.000000e+00,33254,2.766863e+09
4,Other Health,12.0,3.721920e+05,36035,3.172545e+09
5,Hospitals and Nursing Homes,2.0,1.350000e+04,5998,2.282546e+09
6,Human Services,51.0,1.346308e+07,114785,8.401092e+09
7,"International, Foreign Affairs",25.0,4.193049e+06,19062,2.761109e+09
8,"Public, Societal Benefit",1136.0,3.925731e+09,51014,9.097285e+09
9,Religion Related,64.0,1.118393e+08,70673,4.811374e+09
10,"Unknown, Unclassified",0.0,0.000000e+00,4136,4.295551e+08

### Output results

In [165]:
# Output the recipient summary table to csv

# Archive old output file if present

if os.path.exists(recipient_summary_path):

    # Get modification time of existing file
    old_timestamp = datetime.fromtimestamp(
        os.path.getmtime(recipient_summary_path)
    ).strftime("%Y%m%d_%H%M%S")

    archived_filename = (
        f"{recipient_summary_file}_archived_{old_timestamp}.csv"
    )

    archived_path = os.path.join(
        output_directory,
        archived_filename
    )

    os.rename(
        recipient_summary_path,
        archived_path
    )

    print(
        "Archived existing file:",
        archived_path
    )

combined_recipient_summary.to_csv(recipient_summary_path, index=False)

Archived existing file: ..\data\nonprofit_economy\DAF_grants_summary_by_recipient_NTEE_archived_20260701_122213.csv