### Load packages

In [1]:
import pandas as pd
import os
import numpy as np
from datetime import datetime

### Define parameters and file info

In [3]:
# -----------------------------------------------------------------------
# Directory info
# -----------------------------------------------------------------------

github_data_directory = r"..\data\nonprofit_economy"
area990_data_directory = r"..\..\..\Documents\Work\IPS\Area 990\Data Sources\Foundations\Grants\csvs"

bmf_directory = r"..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\EO BMF Files"
ntee_directory = r"..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV"

output_directory = r"..\data\nonprofit_economy"

# -----------------------------------------------------------------------
# All-DAF data
# -----------------------------------------------------------------------
pf_file = r"pf_grants_29mo_2023_20260607_163802.csv"
pf_path = os.path.join(area990_data_directory, pf_file)
print(
    "PF grants CSV file:",
    pf_path,
    "EXISTS" if os.path.exists(pf_path) else "MISSING"
)

# -----------------------------------------------------------------------
# NTEE data
# -----------------------------------------------------------------------

ntee_file = r"eo_bmf_extract_narrow"
ntee_path = os.path.join(ntee_directory, ntee_file + ".csv")
print(
    "NTEE file:",
    ntee_path,
    "EXISTS" if os.path.exists(ntee_path) else "MISSING"
)

# -----------------------------------------------------------------------
# Output files
# -----------------------------------------------------------------------

pf_summary_file = r"PF_grants_summary_by_recipient_NTEE"
pf_summary_path = os.path.join(output_directory, pf_summary_file + ".csv")
print("PF Summary file:", pf_summary_path)

PF grants CSV file: ..\..\..\Documents\Work\IPS\Area 990\Data Sources\Foundations\Grants\csvs\pf_grants_29mo_2023_20260607_163802.csv EXISTS
NTEE file: ..\..\..\AppData\Local\Programs\Python\Python310\Lib\site-packages\irsx\CSV\eo_bmf_extract_narrow.csv EXISTS
PF Summary file: ..\data\nonprofit_economy\PF_grants_summary_by_recipient_NTEE.csv

### Load in data

In [4]:
# Load DAF-to-DAF data

pf_raw_df = pd.read_csv(pf_path)

pf_raw_df.head()

C:\Users\hefla\AppData\Local\Temp\ipykernel_40476\635628640.py:3: DtypeWarning: Columns (5,13,14,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  pf_raw_df = pd.read_csv(pf_path)

,Object ID,EIN,Foundation,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,RcpntBsnssNm_BsnssNmLn2Txt,Recipient Name,RcpntUSAddrss_AddrssLn1Txt,RcpntUSAddrss_AddrssLn2Txt,RcpntUSAddrss_CtyNm,...,GrntOrCntrbtnPdDrYr_RcpntPrsnNm,GrntOrCntrbtnPdDrYr_RcpntRltnshpTxt,GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt,GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt,RcpntFrgnAddrss_AddrssLn1Txt,RcpntFrgnAddrss_CtyNm,RcpntFrgnAddrss_PrvncOrSttNm,RcpntFrgnAddrss_CntryCd,RcpntFrgnAddrss_FrgnPstlCd,RcpntFrgnAddrss_AddrssLn2Txt
0,202430209349100108,10024907,BAR HARBOR VILLAGE IMPROVEMENT ASSOCIATION C/O...,2023,BAR HARBOR HISTORICAL SOCIETY,NaN,BAR HARBOR HISTORICAL SOCIETY,127 WEST STREERT,NaN,BAR HARBOR,...,NaN,NaN,501(C)3,DONATION,NaN,NaN,NaN,NaN,NaN,NaN
1,202433209349105868,10131950,PLANT MEMORIAL HOME,2023,PATIENTS OF PLANT ASSISTED LIVING,NaN,PATIENTS OF PLANT ASSISTED LIVING,1 WASHINGTON STREET,NaN,BATH,...,NaN,NaN,I,PROVIDE ASSISTED LIVING FOR PATIENTS,NaN,NaN,NaN,NaN,NaN,NaN
2,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,RIDING TO THE TOP,NaN,RIDING TO THE TOP,14 LILAC DRIVE,NaN,WINDHAM,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN
3,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,SOUTHERN MAINE AGENCY ON AGING,NaN,SOUTHERN MAINE AGENCY ON AGING,30 BARRA RD,NaN,BIDDEFORD,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN
4,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,PORTLAND WIDOWS WOOD SOCIETY,NaN,PORTLAND WIDOWS WOOD SOCIETY,44 BRAMBLEWOOD DRIVE,NaN,PORTLAND,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Load in NTEE data

ntee_raw_df = pd.read_csv(ntee_path)

ntee_raw_df.head()

,EIN,LAST_YEAR_IN_BMF,ORG_NAME_RAW,SUBSECTION_CODE,ORG_ADDR_STATE,NTEE_IRS,NTEE_OLD_BMF,NTEE_CODE_RAW,NTEE_CODE_CLEAN,NTEE_COMBINED,NTEE_SOURCE
0,4,2001.0,SCRIPT INC,3.0,OH,NaN,B90,B90,B90,B90,NCCS_CLEAN
1,5,2004.0,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3.0,GA,NaN,A50,A50,A50,A50,NCCS_CLEAN
2,3154,2016.0,OAKLEAF FOREST TENANT MANAGEMENT,3.0,VA,NaN,C36,C36,C36,C36,NCCS_CLEAN
3,4101,2023.0,SOUTH LAFOURCHE QUARTERBACK CLUB,3.0,LA,NaN,N65,N65,N65,N65,NCCS_CLEAN
4,4882,2004.0,LITTLE LEAGUE BASEBALL INC,3.0,MD,NaN,N63,N63,N63,N63,NCCS_CLEAN

### Clean and format columns

In [6]:
pf_raw_df.columns

Index(['Object ID', 'EIN', 'Foundation', 'Year of Tax Period End Date',
       'RcpntBsnssNm_BsnssNmLn1Txt', 'RcpntBsnssNm_BsnssNmLn2Txt',
       'Recipient Name', 'RcpntUSAddrss_AddrssLn1Txt',
       'RcpntUSAddrss_AddrssLn2Txt', 'RcpntUSAddrss_CtyNm', 'Recipient State',
       'Recipient Zip', 'Grant Amount', 'GrntOrCntrbtnPdDrYr_RcpntPrsnNm',
       'GrntOrCntrbtnPdDrYr_RcpntRltnshpTxt',
       'GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt',
       'GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt',
       'RcpntFrgnAddrss_AddrssLn1Txt', 'RcpntFrgnAddrss_CtyNm',
       'RcpntFrgnAddrss_PrvncOrSttNm', 'RcpntFrgnAddrss_CntryCd',
       'RcpntFrgnAddrss_FrgnPstlCd', 'RcpntFrgnAddrss_AddrssLn2Txt'],
      dtype='object')

In [7]:
# Clean & format columns in pf data

pf_clean_df = pf_raw_df.copy()

# Rename EIN columns
# pf_clean_df.rename(
#     columns={"EIN": "Grantor EIN", "RcpntTbl_RcpntEIN": "pf EIN", "Total DAF Grants": "Grant Amount"},
#    inplace=True
# )

# Convert integer columns to integer format
int_cols = ["EIN"]
pf_clean_df[int_cols] = pf_clean_df[int_cols].astype("Int64")

# Convert grant amount to float
pf_clean_df["Grant Amount"] = pf_clean_df["Grant Amount"].astype(float)

pf_clean_df.head()

,Object ID,EIN,Foundation,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,RcpntBsnssNm_BsnssNmLn2Txt,Recipient Name,RcpntUSAddrss_AddrssLn1Txt,RcpntUSAddrss_AddrssLn2Txt,RcpntUSAddrss_CtyNm,...,GrntOrCntrbtnPdDrYr_RcpntPrsnNm,GrntOrCntrbtnPdDrYr_RcpntRltnshpTxt,GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt,GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt,RcpntFrgnAddrss_AddrssLn1Txt,RcpntFrgnAddrss_CtyNm,RcpntFrgnAddrss_PrvncOrSttNm,RcpntFrgnAddrss_CntryCd,RcpntFrgnAddrss_FrgnPstlCd,RcpntFrgnAddrss_AddrssLn2Txt
0,202430209349100108,10024907,BAR HARBOR VILLAGE IMPROVEMENT ASSOCIATION C/O...,2023,BAR HARBOR HISTORICAL SOCIETY,NaN,BAR HARBOR HISTORICAL SOCIETY,127 WEST STREERT,NaN,BAR HARBOR,...,NaN,NaN,501(C)3,DONATION,NaN,NaN,NaN,NaN,NaN,NaN
1,202433209349105868,10131950,PLANT MEMORIAL HOME,2023,PATIENTS OF PLANT ASSISTED LIVING,NaN,PATIENTS OF PLANT ASSISTED LIVING,1 WASHINGTON STREET,NaN,BATH,...,NaN,NaN,I,PROVIDE ASSISTED LIVING FOR PATIENTS,NaN,NaN,NaN,NaN,NaN,NaN
2,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,RIDING TO THE TOP,NaN,RIDING TO THE TOP,14 LILAC DRIVE,NaN,WINDHAM,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN
3,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,SOUTHERN MAINE AGENCY ON AGING,NaN,SOUTHERN MAINE AGENCY ON AGING,30 BARRA RD,NaN,BIDDEFORD,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN
4,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,PORTLAND WIDOWS WOOD SOCIETY,NaN,PORTLAND WIDOWS WOOD SOCIETY,44 BRAMBLEWOOD DRIVE,NaN,PORTLAND,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Clean & format columns in All-DAF data

pf_clean_df = pf_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["Object ID", "EIN", "Year of Tax Period End Date"]
pf_raw_df[int_cols] = pf_raw_df[int_cols].astype("Int64")

# Clean up dollar formatting in CSV file
dollar_cols = ["Grant Amount"]
# Convert to float
pf_clean_df[dollar_cols] = pf_clean_df[dollar_cols].astype(float)

pf_clean_df.head()

,Object ID,EIN,Foundation,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,RcpntBsnssNm_BsnssNmLn2Txt,Recipient Name,RcpntUSAddrss_AddrssLn1Txt,RcpntUSAddrss_AddrssLn2Txt,RcpntUSAddrss_CtyNm,...,GrntOrCntrbtnPdDrYr_RcpntPrsnNm,GrntOrCntrbtnPdDrYr_RcpntRltnshpTxt,GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt,GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt,RcpntFrgnAddrss_AddrssLn1Txt,RcpntFrgnAddrss_CtyNm,RcpntFrgnAddrss_PrvncOrSttNm,RcpntFrgnAddrss_CntryCd,RcpntFrgnAddrss_FrgnPstlCd,RcpntFrgnAddrss_AddrssLn2Txt
0,202430209349100108,10024907,BAR HARBOR VILLAGE IMPROVEMENT ASSOCIATION C/O...,2023,BAR HARBOR HISTORICAL SOCIETY,NaN,BAR HARBOR HISTORICAL SOCIETY,127 WEST STREERT,NaN,BAR HARBOR,...,NaN,NaN,501(C)3,DONATION,NaN,NaN,NaN,NaN,NaN,NaN
1,202433209349105868,10131950,PLANT MEMORIAL HOME,2023,PATIENTS OF PLANT ASSISTED LIVING,NaN,PATIENTS OF PLANT ASSISTED LIVING,1 WASHINGTON STREET,NaN,BATH,...,NaN,NaN,I,PROVIDE ASSISTED LIVING FOR PATIENTS,NaN,NaN,NaN,NaN,NaN,NaN
2,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,RIDING TO THE TOP,NaN,RIDING TO THE TOP,14 LILAC DRIVE,NaN,WINDHAM,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN
3,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,SOUTHERN MAINE AGENCY ON AGING,NaN,SOUTHERN MAINE AGENCY ON AGING,30 BARRA RD,NaN,BIDDEFORD,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN
4,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,PORTLAND WIDOWS WOOD SOCIETY,NaN,PORTLAND WIDOWS WOOD SOCIETY,44 BRAMBLEWOOD DRIVE,NaN,PORTLAND,...,NaN,GRANT CANDIDATE,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN

### Clean and format columns in NTEE data

In [9]:
ntee_raw_df.columns

Index(['EIN', 'LAST_YEAR_IN_BMF', 'ORG_NAME_RAW', 'SUBSECTION_CODE',
       'ORG_ADDR_STATE', 'NTEE_IRS', 'NTEE_OLD_BMF', 'NTEE_CODE_RAW',
       'NTEE_CODE_CLEAN', 'NTEE_COMBINED', 'NTEE_SOURCE'],
      dtype='object')

In [11]:
# Clean & format columns in NTEE data

ntee_clean_df = ntee_raw_df.copy()

# Convert integer columns to integer format
int_cols = ["EIN", "SUBSECTION_CODE"]
ntee_clean_df[int_cols] = ntee_clean_df[int_cols].astype("Int64")

# Drop unnecessary columns
cols_to_drop = ["ORG_ADDR_STATE", "NTEE_OLD_BMF", "NTEE_IRS", "NTEE_CODE_RAW", "NTEE_CODE_CLEAN", "NTEE_SOURCE"]
ntee_clean_df = ntee_clean_df.drop(columns=cols_to_drop)

# Uppercase NTEE_COMBINED
ntee_clean_df["NTEE_COMBINED"] = ntee_clean_df["NTEE_COMBINED"].str.upper()

# Create one-digit NTEE code columm
ntee_clean_df["NTEE_FIRST_DIGIT"] = ntee_clean_df["NTEE_COMBINED"].str[0]

# Identify invalid first digits (not A-Z or null/NaN) and replace with "0"
ntee_clean_df["NTEE_FIRST_DIGIT"] = ntee_clean_df["NTEE_FIRST_DIGIT"].mask(
    ntee_clean_df["NTEE_FIRST_DIGIT"].isna() | ~ntee_clean_df["NTEE_FIRST_DIGIT"].str.match(r"^[A-Z]$", na=False),
    "0"
)

ntee_clean_df.head()

,EIN,LAST_YEAR_IN_BMF,ORG_NAME_RAW,SUBSECTION_CODE,NTEE_COMBINED,NTEE_FIRST_DIGIT
0,4,2001.0,SCRIPT INC,3,B90,B
1,5,2004.0,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3,A50,A
2,3154,2016.0,OAKLEAF FOREST TENANT MANAGEMENT,3,C36,C
3,4101,2023.0,SOUTH LAFOURCHE QUARTERBACK CLUB,3,N65,N
4,4882,2004.0,LITTLE LEAGUE BASEBALL INC,3,N63,N

In [12]:
# Find records where NTEE_COMBINED is null or 0

# Rows where NTEE_FIRST_DIGIT is NaN or not A-Z
invalid_ntee_rows = ntee_clean_df[
    ntee_clean_df["NTEE_FIRST_DIGIT"].isna() |        # null/NaN
    ~ntee_clean_df["NTEE_FIRST_DIGIT"].str.match(r"^[A-Z]$", na=False)  # not a single uppercase letter
]

# print(invalid_ntee_rows.value_counts())
# Show the results
# print(invalid_ntee_rows)
print("Number of invalid NTEE codes:", len(invalid_ntee_rows))

Number of invalid NTEE codes: 64854

In [13]:
# Dedupe the NTEE file

ntee_valid_df = ntee_clean_df.copy()
print("Before deduping:", len(ntee_valid_df))

# Find rows with valid NTEE codes
ntee_valid_df["is_valid_ntee"] = (
    ntee_valid_df["NTEE_FIRST_DIGIT"]
    .astype(str)
    .str.match("^[A-Za-z]$")
)

# Make sure the year is numeric
ntee_valid_df["LAST_YEAR_IN_BMF"] = pd.to_numeric(ntee_valid_df["LAST_YEAR_IN_BMF"], errors="coerce")

# Sort by EIN, valid ntee code flag, and LAST_YEAR_IN_BMF
ntee_sorted_df = ntee_valid_df.sort_values(
    by=["EIN", "is_valid_ntee", "LAST_YEAR_IN_BMF"],
    ascending=[True, False, False]
)

# Keep only the first record for each EIN
ntee_dedupe_df = ntee_sorted_df.drop_duplicates(subset="EIN", keep="first")

# Drop the helper column
ntee_dedupe_df = ntee_dedupe_df.drop(columns=["is_valid_ntee"])

print("After deduping:", len(ntee_dedupe_df))

ntee_dedupe_df.head()

Before deduping: 3687435
After deduping: 3687435

,EIN,LAST_YEAR_IN_BMF,ORG_NAME_RAW,SUBSECTION_CODE,NTEE_COMBINED,NTEE_FIRST_DIGIT
0,4,2001.0,SCRIPT INC,3,B90,B
1,5,2004.0,JEKYLL ISLAND MUSEUM ASSOCIATES INC,3,A50,A
2,3154,2016.0,OAKLEAF FOREST TENANT MANAGEMENT,3,C36,C
3,4101,2023.0,SOUTH LAFOURCHE QUARTERBACK CLUB,3,N65,N
4,4882,2004.0,LITTLE LEAGUE BASEBALL INC,3,N63,N

In [14]:
# Check presence of duplicate rows
duplicates_df = ntee_dedupe_df[ntee_dedupe_df["EIN"].duplicated(keep=False)]

print(f"Total duplicate rows: {len(duplicates_df)}")
# duplicates_df.head(10)

Total duplicate rows: 0

### Add NTEE codes to All-DAF grants file

In [15]:
pf_clean_df.columns

Index(['Object ID', 'EIN', 'Foundation', 'Year of Tax Period End Date',
       'RcpntBsnssNm_BsnssNmLn1Txt', 'RcpntBsnssNm_BsnssNmLn2Txt',
       'Recipient Name', 'RcpntUSAddrss_AddrssLn1Txt',
       'RcpntUSAddrss_AddrssLn2Txt', 'RcpntUSAddrss_CtyNm', 'Recipient State',
       'Recipient Zip', 'Grant Amount', 'GrntOrCntrbtnPdDrYr_RcpntPrsnNm',
       'GrntOrCntrbtnPdDrYr_RcpntRltnshpTxt',
       'GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt',
       'GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt',
       'RcpntFrgnAddrss_AddrssLn1Txt', 'RcpntFrgnAddrss_CtyNm',
       'RcpntFrgnAddrss_PrvncOrSttNm', 'RcpntFrgnAddrss_CntryCd',
       'RcpntFrgnAddrss_FrgnPstlCd', 'RcpntFrgnAddrss_AddrssLn2Txt'],
      dtype='object')

In [19]:
# Add NTEE codes to pf file

print("Before merging:", len(pf_clean_df))
print(pf_clean_df["Grant Amount"].sum())

pf_ntee_df = (
    pf_clean_df
    .merge(
        ntee_dedupe_df[["EIN", "NTEE_COMBINED", "NTEE_FIRST_DIGIT"]],
        left_on=["EIN"],
        right_on=["EIN"],
        how="left",
        indicator=True
    )
)

# Drop helper columns
pf_ntee_df = pf_ntee_df.drop(columns=["_merge"])

# Rename columns
# pf_ntee_df = pf_ntee_df.rename(
#     columns={
#         "NTEE_COMBINED": "GRANTOR_NTEE_COMBINED",
#         "NTEE_FIRST_DIGIT": "GRANTOR_NTEE_FIRST_DIGIT"
#     }
#)

print("After merging:", len(pf_ntee_df))
print(pf_ntee_df["Grant Amount"].sum())

pf_ntee_df.head()

Before merging: 2013937
121773361531.0
After merging: 2013937
121773361531.0

,Object ID,EIN,Foundation,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,RcpntBsnssNm_BsnssNmLn2Txt,Recipient Name,RcpntUSAddrss_AddrssLn1Txt,RcpntUSAddrss_AddrssLn2Txt,RcpntUSAddrss_CtyNm,...,GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt,GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt,RcpntFrgnAddrss_AddrssLn1Txt,RcpntFrgnAddrss_CtyNm,RcpntFrgnAddrss_PrvncOrSttNm,RcpntFrgnAddrss_CntryCd,RcpntFrgnAddrss_FrgnPstlCd,RcpntFrgnAddrss_AddrssLn2Txt,NTEE_COMBINED,NTEE_FIRST_DIGIT
0,202430209349100108,10024907,BAR HARBOR VILLAGE IMPROVEMENT ASSOCIATION C/O...,2023,BAR HARBOR HISTORICAL SOCIETY,NaN,BAR HARBOR HISTORICAL SOCIETY,127 WEST STREERT,NaN,BAR HARBOR,...,501(C)3,DONATION,NaN,NaN,NaN,NaN,NaN,NaN,S20,S
1,202433209349105868,10131950,PLANT MEMORIAL HOME,2023,PATIENTS OF PLANT ASSISTED LIVING,NaN,PATIENTS OF PLANT ASSISTED LIVING,1 WASHINGTON STREET,NaN,BATH,...,I,PROVIDE ASSISTED LIVING FOR PATIENTS,NaN,NaN,NaN,NaN,NaN,NaN,A80,A
2,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,RIDING TO THE TOP,NaN,RIDING TO THE TOP,14 LILAC DRIVE,NaN,WINDHAM,...,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN,L99,L
3,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,SOUTHERN MAINE AGENCY ON AGING,NaN,SOUTHERN MAINE AGENCY ON AGING,30 BARRA RD,NaN,BIDDEFORD,...,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN,L99,L
4,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,PORTLAND WIDOWS WOOD SOCIETY,NaN,PORTLAND WIDOWS WOOD SOCIETY,44 BRAMBLEWOOD DRIVE,NaN,PORTLAND,...,PC,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN,L99,L

### Create summaries by NTEE code

In [20]:
# Function to calculate Shonni's summary groupings on 

def shonni_groups(row, first_digit_ntee_code, full_ntee_code):

    code = row[first_digit_ntee_code]
    combined = str(row[full_ntee_code]).upper() if pd.notna(row[full_ntee_code]) else ""
    
    if pd.isna(code):
        return None
    
    code = str(code).upper()

    if combined.startswith(("T30", "T31", "T32")): # private foundations, community foundations, and corporate foundations
        return "Foundations"
    
    if code == "A":
        return "Arts, Culture, Humanities"
    
    elif code == "B":
        if combined.startswith(("B40", "B41", "B43", "B50")):
            return "Colleges and Universities"
        else:
            return "Other Education"
    
    elif code in ["C", "D"]:
        return "Environment and Animals"
    
    elif code in ["E", "F", "G", "H"]:
        if combined.startswith(("E20", "E21", "E22", "E24", "E90", "E91", "E92")):
            return "Hospitals and Nursing Homes"
        else:
            return "Other Health"
    
    elif code in ["I", "J", "K", "L", "M", "N", "O", "P"]:
        return "Human Services"
    
    elif code == "Q":
        return "International, Foreign Affairs"
    
    elif code in ["R", "S", "T", "U", "V", "W"]:
        return "Public, Societal Benefit"
    
    elif code == "X":
        return "Religion Related"
    

    elif code in ["Y", "Z"]:
        return "Unknown, Unclassified"
    
    else:
        return None

In [21]:
pf_ntee_df.columns

Index(['Object ID', 'EIN', 'Foundation', 'Year of Tax Period End Date',
       'RcpntBsnssNm_BsnssNmLn1Txt', 'RcpntBsnssNm_BsnssNmLn2Txt',
       'Recipient Name', 'RcpntUSAddrss_AddrssLn1Txt',
       'RcpntUSAddrss_AddrssLn2Txt', 'RcpntUSAddrss_CtyNm', 'Recipient State',
       'Recipient Zip', 'Grant Amount', 'GrntOrCntrbtnPdDrYr_RcpntPrsnNm',
       'GrntOrCntrbtnPdDrYr_RcpntRltnshpTxt',
       'GrntOrCntrbtnPdDrYr_RcpntFndtnSttsTxt',
       'GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt',
       'RcpntFrgnAddrss_AddrssLn1Txt', 'RcpntFrgnAddrss_CtyNm',
       'RcpntFrgnAddrss_PrvncOrSttNm', 'RcpntFrgnAddrss_CntryCd',
       'RcpntFrgnAddrss_FrgnPstlCd', 'RcpntFrgnAddrss_AddrssLn2Txt',
       'NTEE_COMBINED', 'NTEE_FIRST_DIGIT'],
      dtype='object')

In [24]:
# Apply Shonni groupings to daf-to-daf grants by pf NTEE code

pf_groupings_df = pf_ntee_df.copy()

pf_groupings_df["NTEE_ACTIVITY"] = pf_groupings_df.apply(
    shonni_groups,
    axis=1,
    args=("NTEE_FIRST_DIGIT", "NTEE_COMBINED")
)

pf_groupings_df.head()

,Object ID,EIN,Foundation,Year of Tax Period End Date,RcpntBsnssNm_BsnssNmLn1Txt,RcpntBsnssNm_BsnssNmLn2Txt,Recipient Name,RcpntUSAddrss_AddrssLn1Txt,RcpntUSAddrss_AddrssLn2Txt,RcpntUSAddrss_CtyNm,...,GrntOrCntrbtnPdDrYr_GrntOrCntrbtnPrpsTxt,RcpntFrgnAddrss_AddrssLn1Txt,RcpntFrgnAddrss_CtyNm,RcpntFrgnAddrss_PrvncOrSttNm,RcpntFrgnAddrss_CntryCd,RcpntFrgnAddrss_FrgnPstlCd,RcpntFrgnAddrss_AddrssLn2Txt,NTEE_COMBINED,NTEE_FIRST_DIGIT,NTEE_ACTIVITY
0,202430209349100108,10024907,BAR HARBOR VILLAGE IMPROVEMENT ASSOCIATION C/O...,2023,BAR HARBOR HISTORICAL SOCIETY,NaN,BAR HARBOR HISTORICAL SOCIETY,127 WEST STREERT,NaN,BAR HARBOR,...,DONATION,NaN,NaN,NaN,NaN,NaN,NaN,S20,S,"Public, Societal Benefit"
1,202433209349105868,10131950,PLANT MEMORIAL HOME,2023,PATIENTS OF PLANT ASSISTED LIVING,NaN,PATIENTS OF PLANT ASSISTED LIVING,1 WASHINGTON STREET,NaN,BATH,...,PROVIDE ASSISTED LIVING FOR PATIENTS,NaN,NaN,NaN,NaN,NaN,NaN,A80,A,"Arts, Culture, Humanities"
2,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,RIDING TO THE TOP,NaN,RIDING TO THE TOP,14 LILAC DRIVE,NaN,WINDHAM,...,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN,L99,L,Human Services
3,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,SOUTHERN MAINE AGENCY ON AGING,NaN,SOUTHERN MAINE AGENCY ON AGING,30 BARRA RD,NaN,BIDDEFORD,...,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN,L99,L,Human Services
4,202343399349100504,10211504,THE EUNICE FRYE HOME FOUNDATION CO THOMAS M PI...,2023,PORTLAND WIDOWS WOOD SOCIETY,NaN,PORTLAND WIDOWS WOOD SOCIETY,44 BRAMBLEWOOD DRIVE,NaN,PORTLAND,...,GRANT TO BENEFIT PEOPLE OF GREATER PORTLAND AREA.,NaN,NaN,NaN,NaN,NaN,NaN,L99,L,Human Services

In [25]:
# Define activity area sort order

activity_order = ["Arts, Culture, Humanities", "Other Education", "Colleges and Universities", "Environment and Animals", "Other Health", 
         "Hospitals and Nursing Homes", "Human Services", "International, Foreign Affairs", "Public, Societal Benefit",
         "Foundations", "Religion Related", "Unknown, Unclassified"]

In [26]:
# Create summary of daf-to-daf data

pf_summary_df = pf_groupings_df.copy()

pf_summary_df["NTEE_ACTIVITY"] = pf_summary_df.apply(
    shonni_groups,
    axis=1,
    args=("NTEE_FIRST_DIGIT", "NTEE_COMBINED")
)

pf_summary = (
    pf_summary_df
    .groupby("NTEE_ACTIVITY", as_index=False)
    .agg(
        Count_of_Orgs=("EIN", "count"),
        Grant_Amount=("Grant Amount", "sum")
    )
)

pf_summary["NTEE_ACTIVITY"] = pd.Categorical(
    pf_summary["NTEE_ACTIVITY"],
    categories=activity_order,
    ordered=True
)

pf_summary = pf_summary.sort_values("NTEE_ACTIVITY")

pf_summary

                     NTEE_ACTIVITY  Count_of_Orgs  Grant_Amount
0        Arts, Culture, Humanities          14731  7.910276e+08
7                  Other Education          87105  5.131654e+09
1        Colleges and Universities            829  6.448358e+07
2          Environment and Animals          11551  4.050957e+08
8                     Other Health          14169  1.205855e+10
4      Hospitals and Nursing Homes           3343  3.006538e+08
5                   Human Services          40315  9.286698e+09
6   International, Foreign Affairs           2861  2.067884e+08
9         Public, Societal Benefit        1788102  9.144338e+10
3                      Foundations          16091  6.210011e+08
10                Religion Related          11485  5.427089e+08
11           Unknown, Unclassified          14078  4.029197e+08

### Output results

In [27]:
# Output the pf summary table to csv

# Archive old output file if present

if os.path.exists(pf_summary_path):

    # Get modification time of existing file
    old_timestamp = datetime.fromtimestamp(
        os.path.getmtime(pf_summary_path)
    ).strftime("%Y%m%d_%H%M%S")

    archived_filename = (
        f"{pf_summary_file}_archived_{old_timestamp}.csv"
    )

    archived_path = os.path.join(
        output_directory,
        archived_filename
    )

    os.rename(
        pf_summary_path,
        archived_path
    )

    print(
        "Archived existing file:",
        archived_path
    )

pf_summary.to_csv(pf_summary_path, index=False)